#! /bin/sh
# $Id: bootstrap 2008 2015-06-04 14:32:56Z dreibh $

set -x

rm -rf admin
mkdir admin

if glibtoolize --version >/dev/null 2>&1 ; then
    LIBTOOLIZE=glibtoolize
elif libtoolize --version >/dev/null 2>&1 ; then
    LIBTOOLIZE=libtoolize
else
   echo "ERROR: I cannot find libtoolize or glibtoolize!"
   exit 1
fi

ACLOCALDIR=
if [ -e /usr/local/share/aclocal ] ; then
   ACLOCALDIR=/usr/local/share/aclocal
elif [ -e /usr/share/aclocal ] ; then
   ACLOCALDIR=/usr/share/aclocal
else
   echo >&2 "ERROR: No aclocal directory found!"
   exit 1
fi

ACLOCAL=${ACLOCAL:-aclocal}
AUTOHEADER=${AUTOHEADER:-autoheader}
AUTOMAKE=${AUTOMAKE:-automake}
AUTOCONF=${AUTOCONF:-autoconf}

"$LIBTOOLIZE" --force
"$ACLOCAL" -I "$ACLOCALDIR"
"$AUTOHEADER"
"$AUTOMAKE" --gnu --add-missing --copy
"$AUTOCONF"
