#!/usr/bin/perl
#
# Debian/Ubuntu Packaging Scripts
# Copyright (C) 2002-2022 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


# This script filters debian/changelog entries:
# Usage: filter-empty-entries [regexp_for_last_entry|FIRST]
# * Empty entries get dropped.
# * Stop, if entry matches regexp_for_last_entry argument.
# * Stop after first entry, if regexp_for_last_entry = FIRST.


use warnings;
use strict;

my $entries           = 0;
my $entryContentLines = 0;
my $entryContent      = "";

while (my $text = <STDIN>) {
   chomp $text;

   # ====== Begin of entry ==================================================
   if($entryContentLines == 0) {
      if($text =~ /^[a-zA-Z].*$/) {
         $entryContent      = "$text\n\n";
         $entryContentLines = 1;
      }
   }

   # ====== Within entry ====================================================
   else {
      # ------ End of entry -------------------------------------------------
      if($text =~ /^ --.*$/) {
         $entryContent  = "$entryContent\n$text\n";
         if($entryContentLines > 1) {
            $entries = $entries + 1;
            print "$entryContent\n";
         }

         # ------ Check for match with last entry regexp in argument --------
         if($ARGV[0] !~ /^$/) {
            if( ($ARGV[0] =~ "FIRST") || ($text =~ /($ARGV[0])/) ) {
               exit;
            }
         }

         $entryContentLines = 0;
      }
      # ------ Part of entry ------------------------------------------------
      else {
         if($text !~ /^[ \t]*$/) {   # Not an empty line
            $entryContent      = "$entryContent$text\n";
            $entryContentLines = $entryContentLines + 1;
         }
      }
   }
}
