#!/usr/bin/env bash
#
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2024 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -eu

echo "Testing HiPerConTracer with ICMP in the Internet ..."

# Prepare results directory writable by user "hipercontracer":
mkdir -p results1
sudo chown hipercontracer:hipercontracer results1

echo "Default IPs: "
get-default-ips

# Run HiPerConTracer:
sudo hipercontracer \
   -# 12345678 \
   --user hipercontracer \
   --source 0.0.0.0 --source :: \
   --destination www.ietf.org \
   --ping --traceroute \
   --iterations=1 \
   --resultscompression BZip2 \
   -R results1

bzcat results1/*-#12345678*.results.bz2

echo "Test passed!"
