.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2024 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd September 25, 2015
.Dt addressinfogenerator 1
.Os addressinfogenerator
.\" ###### Name #############################################################
.Sh NAME
.Nm addressinfogenerator
.Nd HiPerConTracer Address Info Generator
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm addressinfogenerator
database_configuration
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm addressinfogenerator
updates the HiPerConTracer PostgreSQL database with additional information
on observed IP addresses: geo location (obtained by GeoIP), Autonomous System
(ASN) information (obtained by GeoIP) and a DNS reverse lookup.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following argument has to be provided:
.Bl -tag -width indent
.It database_configuration
Specifies the database configuration file. See
/usr/share/hipercontracer/hipercontracer-database-configuration
for an example.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It addressinfogenerator hipercontracer-database-configuration
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/addressinfogenerator
.br
mailto://dreibh@simula.no
.br
