#!/bin/bash -e

# A simple fix for the old "2.0.0~beta1" format, to add port numbers,
# and also set a new ID.

ID=20230001
SPORT=0
DPORT=0

while [ $# -gt 0 ] ; do
   xzcat $1 | sed \
      -e "s%^\(#T.\) \([0-9]*\) \(.*\) \([0-9a-f]*\) \([0-9a-f]*\)$%\1 $ID \3 $SPORT $DPORT \4 \5%g" \
      -e "s%^\(#P.\) \([0-9]*\) \([0-9a-f\.:]* [0-9a-f\.:]* [0-9a-f]* [0-9a-f]* [0-9a-f]* [0-9a-f]* [0-9a-f]* [0-9a-f]*\) \([0-9a-f]* [0-9a-f]* [0-9a-f-]* [0-9a-f-]* [0-9a-f-]* [0-9a-f-]* [0-9a-f-]* [0-9a-f-]*\)$%\1 $ID \3 $SPORT $DPORT \4%g"
   shift
done
