#!/usr/bin/python3
# -*- coding: utf-8 -*-

# ====== Trace configuration ================================================
transactions_path = /tmp/xy
bad_file_path     = /tmp/xy/bad
good_file_path    = /tmp/xy/good

# ====== Database configuration =============================================
database          = pingtraceroutedb
dbuser            = importer
dbpassword        = !importer!

# ====== Database server ====================================================
# ****** Configuration with MongoDB server: ******
dbbackend         = MongoDB
dbserver          = rolfsbukta.alpha.test
dbport            = 27017
dbcafile          = IGNORE

# ****** Configuration with PostgreSQL server: ******
# dbbackend         = PostgreSQL
# dbserver          = rolfsbukta.alpha.test
# dbport            = 5432
# dbcafile          = IGNORE

