#!/usr/bin/env bash

set -eux

DIRECTORY="/tmp/test"

rm -rf "${DIRECTORY}/data"
mkdir -p "${DIRECTORY}/data"
for n in 9000 9001 9002 9003 ; do
   userdel "node$n" || true
   rm -rf "${DIRECTORY}/data/node$n"
   mkdir "${DIRECTORY}/data/node$n"
   useradd -M -d "${DIRECTORY}/data/node$n" -s /bin/sh -c "User $n" "node$n"

   chown "node$n:hipercontracer" "${DIRECTORY}/data/node$n"
   chmod 2770 "${DIRECTORY}/data/node$n"

   sudo -u "node$n" mkdir -p "${DIRECTORY}/data/node$n/test"
   sudo -u "node$n" chmod 770 "${DIRECTORY}/data/node$n/test"
   date | sudo -u "node$n" tee >/dev/null "${DIRECTORY}/data/node$n/test/x.txt"
   date | sudo -u "node$n" tee >/dev/null "${DIRECTORY}/data/node$n/test/y.txt"
   date | sudo -u "node$n" tee >/dev/null "${DIRECTORY}/data/node$n/test/z.txt"
done
grep "^node" /etc/passwd


for n in 9001 9002 9003 ; do
   if [ $n -eq 9001 ] ; then
      sudo -u "node$n" mkdir -p "${DIRECTORY}/data/node9001/test"
   else
      if sudo -u "node$n" mkdir -p "${DIRECTORY}/data/node9001/test" ; then
         echo "This command must fail, but it did not!"
         exit 1
      fi
   fi
done

for n in 9001 9002 9003 ; do
   sudo -u hipercontracer cat "${DIRECTORY}/data/node$n/test/x.txt"
   sudo -u hipercontracer rm -f "${DIRECTORY}/data/node$n/test/y.txt"
   date | sudo -u hipercontracer tee >/dev/null "${DIRECTORY}/data/node$n/test/h.txt"
done

ls -al ${DIRECTORY}/data/
