#!/usr/bin/env bash

set -eux

for n in 9000 9001 9002 9003 ; do
   userdel "node$n" || true
   rm -rf "/var/hipercontracer/data/node$n"
   mkdir "/var/hipercontracer/data/node$n"
   useradd -M -d "/var/hipercontracer/data/node$n" -s /bin/sh -c "User $n" "node$n"

   chown "node$n:hipercontracer" "/var/hipercontracer/data/node$n"
   chmod 2770 "/var/hipercontracer/data/node$n"

   sudo -u "node$n" mkdir -p "/var/hipercontracer/data/node$n/test"
   sudo -u "node$n" chmod 770 "/var/hipercontracer/data/node$n/test"
   date | sudo -u "node$n" tee >/dev/null "/var/hipercontracer/data/node$n/test/x.txt"
   date | sudo -u "node$n" tee >/dev/null "/var/hipercontracer/data/node$n/test/y.txt"
   date | sudo -u "node$n" tee >/dev/null "/var/hipercontracer/data/node$n/test/z.txt"
done
grep "^node" /etc/passwd


for n in 9001 9002 9003 ; do
   if [ $n -eq 9001 ] ; then
      sudo -u "node$n" mkdir -p "/var/hipercontracer/data/node9001/test"
   else
      if sudo -u "node$n" mkdir -p "/var/hipercontracer/data/node9001/test" ; then
         echo "This command must fail, but it did not!"
         exit 1
      fi
   fi
done

for n in 9001 9002 9003 ; do
   sudo -u hipercontracer cat "/var/hipercontracer/data/node$n/test/x.txt"
   sudo -u hipercontracer rm -f "/var/hipercontracer/data/node$n/test/y.txt"
   date | sudo -u hipercontracer tee >/dev/null "/var/hipercontracer/data/node$n/test/h.txt"
done

ls -al /var/hipercontracer/data/
