.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2024 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd September 25, 2015
.Dt tracedataimporter 1
.Os tracedataimporter
.\" ###### Name #############################################################
.Sh NAME
.Nm tracedataimporter
.Nd HiPerConTracer Trace Data Importer
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm tracedataimporter
database_configuration
.Op \-verbose
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm tracedataimporter
imports the SQL statements written by HiPerConTracer into a PostgreSQL
database. If a file has been imported successfully, it is deleted. In case of
an import failure, the file is moved to a "bad file" directory.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following argument has to be provided:
.Bl -tag -width indent
.It database_configuration
Specifies the database configuration file. See
/usr/share/hipercontracer/hipercontracer-database-configuration
for an example.
.It \-verbose
Print the name of each transaction file before importing it.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It tracedataimporter hipercontracer-database-configuration
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/hipercontracer
.br
mailto://dreibh@simula.no
.br
