#!/bin/bash -e
#
# FreeBSD Ports Packaging Scripts
# Copyright (C) 2017-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

PORTNAME=`grep "PORTNAME=" Makefile | gsed -e 's/^.*=//g' -e 's/[ \t]*//g'`
PORTVERSION=`grep "PORTVERSION=" Makefile | gsed -e 's/^.*=//g' -e 's/[ \t]*//g'`
LOCATION=`grep "MASTER_SITES=" Makefile | gsed -e 's/^.*=//g' -e 's/[ \t]*//g'`

echo "PORTNAME:    $PORTNAME"
echo "PORTVERSION: $PORTVERSION"
echo "LOCATION:    $LOCATION"

if [ ! -e "/usr/ports/distfiles/$PORTNAME-$PORTVERSION.tar.gz" ] ; then
   wget "$LOCATION/$PORTNAME-$PORTVERSION.tar.gz"
   echo "Copying $PORTNAME-$PORTVERSION.tar.gz to /usr/ports/distfiles/ ..."
   sudo mv "$PORTNAME-$PORTVERSION.tar.gz" /usr/ports/distfiles/
fi

echo "Updating checksum ..."
make makesum

echo "Done!"
