#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2024 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -o nounset
set -o errexit


if [ $# -ne 1 ] ; then
   echo >&2 "Usage: $0 users.conf"
   exit 1
fi
CONFIG="$1"


# ====== Generate secure test user passwords ================================
if [ ! -e "${CONFIG}" ] ; then
   echo -e "\x1b[34mGenerating ${CONFIG} ...\x1b[0m"
   while read -r line ; do
      echo >&2 "$line"
      if [[ "${line}" =~ ^(.*[\"])(!.*!)([\"])$ ]] ; then
         echo "${BASH_REMATCH[1]}$(pwgen -s 128)${BASH_REMATCH[3]}"
      else
         echo "${line}"
      fi
   done <users.conf.example | tee "${CONFIG}"
fi

# shellcheck disable=SC1090
. "${CONFIG}"


# ====== Write HiPerConTracer Importer configuration files ==================
name="$(dirname "${CONFIG}")/importer.conf"
cat >"${name}" <<EOF
# ====== Importer Configuration =============================================

# Import modes: DeleteImportedFiles MoveImportedFiles KeepImportedFiles
# DeleteImportedFiles = Delete successfully imported files
# MoveImportedFiles   = Move successfully imported files to good path
# KeepImportedFiles   = Keep successfully imported files where they are
#                       Use only for debugging! Any importer rerun will process them again!
import_mode        = MoveImportedFiles

# Regular expression to filter input files:
import_path_filter =

# Import directory and maximum search depth (1 = only the directory itself):
import_file_path   = data/
import_max_depth   = 6

# NOTE: good and bad file directories MUST NOT be a subdirectory of the
#       import directory!
bad_file_path      = bad/
good_file_path     = good/
EOF

for backend in MariaDB PostgreSQL MongoDB ; do
   for user in maintainer researcher importer ; do
      # shellcheck disable=SC2001
      name="$(echo "${CONFIG}" | sed -e "s/.users\.conf$/-${user}-${backend,,}.conf/")"
      if [ "${user}" == "maintainer" ] ; then
         password="${MAINTAINER_PASSWORD}"
      elif [ "${user}" == "researcher" ] ; then
         password="${RESEARCHER_PASSWORD}"
      elif [ "${user}" == "importer" ] ; then
         password="${IMPORTER_PASSWORD}"
      fi

      cat >"${name}" <<EOF
# ====== Database Server Configuration ======================================

# ----- TLS configuration options -------------------------------------------
# NOTE:
# dbcafile sets a TLS CA file.
# dbcertkeyfile sets a TLS client certificate file.
# dbconnectionflags sets TLS connection flags (space-separated):
# * NONE: default, i.e. require properly configured TLS
# * DisableTLS: disable TLS
# * AllowInvalidHostname: allow invalid hostnames in certificate
# * AllowInvalidCertificate: allow invalid certificate
# WARNING: Do *not* use these options! Instead, configure TLS properly!!
# ---------------------------------------------------------------------------


# ****** Configuration with ${backend} server: ***************
dbbackend         = ${backend}
dbserver          = localhost
dbport            = 0
dbcafile          = /etc/ssl/TestLevel1/certs/TestLevel1.crt
dbcrlfile         = /etc/ssl/TestGlobal.crl
dbcertfile        = NONE
dbkeyfile         = NONE
dbconnectionflags = NONE
dbuser            = ${user}
dbpassword        = ${password}
database          = ${DATABASE}
dbreconnectdelay  = 5
EOF
      if [ "${backend}" == "MongoDB" ] ; then
         sed -e "s/^dbcertfile   /dbcertkeyfile/" \
             -e "/^dbkeyfile/d" \
             <"${name}" >"${name}".new && \
         mv "${name}".new "${name}"
      fi
   done
done
