#!/bin/bash -e

if [ $# -ne 1 ] ; then
   echo >&2 "Usage: $0 mariadb|postgres|mongodb"
   exit 1
fi


# ###### MariaDB ############################################################
if [ "$1" == "mariadb" ] ; then
   # Documentation: https://www.digitalocean.com/community/tutorials/how-to-install-mariadb-on-ubuntu-22-04

   echo "Preparing admin user for MariaDB ..."



# ###### PostgreSQL #########################################################
elif [ "$1" == "postgres" ] ; then
   # Documentation: https://www.digitalocean.com/community/tutorials/how-to-install-postgresql-on-ubuntu-22-04-quickstart

   echo "Preparing admin user for PostgreSQL ..."



# ###### MongoDB ############################################################
elif [ "$1" == "mongodb" ] ; then
   # Documentation: https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/

   echo "Preparing admin user for MongoDB ..."

   echo "Creating maintainer ..."
   mongo --quiet <<EOF
use admin
db.dropUser("maintainer")
db.createUser({ user: "maintainer",
                pwd: "!maintainer!",
                roles: [
                   "userAdminAnyDatabase",
                   "dbAdminAnyDatabase",
                   "readWriteAnyDatabase",
                   "clusterAdmin"
                ] })
EOF


# ###### Error ##############################################################
else
   echo >&2 "ERROR: Unsupported database: $1"
   exit 1
fi
