#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2022 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -o nounset
set -o errexit


if [ $# -ne 2 ] ; then
   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql users.conf"
   exit 1
fi
if [ ! -e $2 ] ; then
   echo >&2 "ERROR: Use configuration $2 does not exist!"
fi

DATABASE="just_a_test_database"
MAINTAINER_PASSWORD=
IMPORTER_PASSWORD=
RESEARCHER_PASSWORD=
. $2


# ###### MySQL/MariaDB ######################################################
if [ "$1" == "mysql" -o "$1" == "mariadb" ] ; then
   # Documentation: https://www.digitalocean.com/community/tutorials/how-to-install-mariadb-on-ubuntu-22-04

   echo -e "\x1b[34mTesting access to MySQL/MariaDB database ...\x1b[0m"
   cat mysql-test.sql | mysql \
      --host=localhost \
      --ssl --ssl-verify-server-cert --ssl-ca=/etc/ssl/TestRoot/certs/TestRoot.crt \
      --user=researcher --password="${RESEARCHER_PASSWORD}" \
      --database="${DATABASE}"


# ###### PostgreSQL #########################################################
elif [ "$1" == "postgresql" ] ; then
   # Documentation: https://www.digitalocean.com/community/tutorials/how-to-install-postgresql-on-ubuntu-22-04-quickstart

   echo -e "\x1b[34mTesting access to PostgreSQL database ...\x1b[0m"
   PGPASSWORD="${RESEARCHER_PASSWORD}" psql -h localhost -U researcher -d "${DATABASE}" <postgresql-test.sql


# ###### MongoDB ############################################################
elif [ "$1" == "mongodb" ] ; then
   # Documentation: https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/

   echo -e "\x1b[34mTesting access to MongoDB database ...\x1b[0m"
   mongosh --tls --tlsCAFile /etc/ssl/TestRoot/certs/TestRoot.crt \
      "mongodb://localhost/${DATABASE}" --username researcher --password "${RESEARCHER_PASSWORD}" --quiet <mongodb-test.ms


# ###### Error ##############################################################
else
   echo >&2 "ERROR: Unsupported database: $1"
   exit 1
fi
