#!/usr/bin/env bash
# ==========================================================================
#     _   _ _ ____            ____          _____
#    | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
#    | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
#    |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
#    |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
#
#       ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
#                 https://www.nntb.no/~dreibh/hipercontracer/
# ==========================================================================
#
# High-Performance Connectivity Tracer (HiPerConTracer)
# Copyright (C) 2015-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -eu


if [ $# -ne 2 ] ; then
   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql users.conf"
   exit 1
fi
if [ ! -e "$2" ] ; then
   echo >&2 "ERROR: Use configuration $2 does not exist!"
fi

DATABASE="just_a_test_database"
# shellcheck disable=SC1090
. "$2"

DBMS="$1"
DATABASE_CONFIG="${HOME}/${DATABASE}-importer-${DBMS}.conf"
IMPORTER_CONFIG="${HOME}/importer-${DATABASE}.conf"

if [ ! -v VALGRIND_CMD ] ; then
   VALGRIND_CMD=""
fi


# ###### Run test ###########################################################
if [ -e "${DATABASE_CONFIG}" ] ; then

   echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Running importer ...\x1b[0m"

   cd ..
   if [ ! -e Makefile ] ; then
      # Running in development environment:
      if [ -x ../autogen.sh ] ; then
         cd ..
         ./autogen.sh
         cd src
      fi
   fi
   if [ -e Makefile ] ; then
      # Running in development environment:
      make hpct-importer
      rm -f core
   fi
   cd TestDB

   mkdir -p data/ good/ bad/
   rm -rf good/*
   rm -rf bad/*

   rsync -a --include='*hpct.*' --include='*results.*' --include='*/' --exclude='*' ../results-examples/ data/
   if [ -x ../hpct-importer ] ; then
      # Running in development environment:
      importer="../hpct-importer"
   else
      importer="hpct-importer"
   fi
   ${VALGRIND_CMD} "${importer}" \
      -C "${IMPORTER_CONFIG}" \
      -D "${DATABASE_CONFIG}" \
      --quit-when-idle \
      --loglevel 2


# ###### Error ##############################################################
else
   echo >&2 "ERROR: ${DATABASE_CONFIG} not found!"
   exit 1
fi
