#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2024 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -o nounset
set -o errexit


if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql"
   exit 1
fi

IMPORTER_CONFIG="${HOME}/importer.conf"
# Access to database as "importer" user:
DBMS="$1"
DATABASE_CONFIG="${HOME}/testdb-importer-${DBMS}.conf"

if [ ! -v VALGRIND_CMD ] ; then
   VALGRIND_CMD=""
fi


# ###### Run test ###########################################################
if [ -e "${DATABASE_CONFIG}" ] ; then

   echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Running importer ...\x1b[0m"

   cd ..
   if [ ! -e Makefile ] ; then
      cd ..
      ./autogen.sh
      cd src
   fi
   make hpct-importer
   rm -f core
   cd TestDB

   mkdir -p data/ good/ bad/
   rm -rf good/*
   rm -rf bad/*

   cp ../examples/*.results.* data/
   ${VALGRIND_CMD} ../hpct-importer \
      -C "${IMPORTER_CONFIG}" \
      -D "${DATABASE_CONFIG}" \
      --quit-when-idle \
      --loglevel 0


# ###### Error ##############################################################
else
   echo >&2 "ERROR: ${DATABASE_CONFIG} not found!"
   exit 1
fi
