#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2024 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -o nounset
set -o errexit


if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql"
   exit 1
fi

# Access to database as "researcher" user:
DBMS="$1"
DATABASE_CONFIG="${HOME}/testdb-researcher-${DBMS}.conf"

if [ ! -v VALGRIND_CMD ] ; then
   VALGRIND_CMD=""
fi


# ###### Run test ###########################################################
if [ -e "${DATABASE_CONFIG}" ] ; then

   echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Querying results ...\x1b[0m"

   if [ ! -e good ] || [ ! -e bad ] || [ ! -e data ] ; then
      echo >&2 "ERROR: Directories missing! Did 5-perform-hpct-importer-test succeed?"
      exit 1
   fi

   for table in Ping Traceroute Jitter ; do

      echo -e "\x1b[33m$(date +"%F %H:%M:%S"): Obtaining ${table} data from good/ directory ...\x1b[0m"
      find good/ -name "${table}-*.results.*" | ../hpct-results --input-file-names-from-stdin -o imported-${table,,}.csv

      echo -e "\x1b[33m$(date +"%F %H:%M:%S"): Querying ${table} data from database ...\x1b[0m"
      ${VALGRIND_CMD} ../hpct-query "${DATABASE_CONFIG}" ${table,,} -o queried-${table,,}-"${DBMS}".results
      ${VALGRIND_CMD} ../hpct-results queried-${table,,}-"${DBMS}".results -o queried-${table,,}-"${DBMS}".csv

      echo -e "\x1b[33m$(date +"%F %H:%M:%S"): Checking for differences in ${table}:\x1b[0m"
      wc -ml imported-${table,,}.csv
      wc -ml queried-${table,,}-"${DBMS}".csv
      if ! diff imported-${table,,}.csv queried-${table,,}-"${DBMS}".csv ; then
         echo "RESULTS DIFFER!"
         diff --color=always imported-${table,,}.csv queried-${table,,}-"${DBMS}".csv | head -n32
         exit 1
      fi

   done

   echo "SUCCESS!"


# ###### Error ##############################################################
else
   echo >&2 "ERROR: ${DATABASE_CONFIG} not found!"
   exit 1
fi
