#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2023 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -o nounset
set -o errexit


if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql"
   exit 1
fi

# Access to database as "researcher" user:
DATABASE_CONFIG="${HOME}/testdb-users-$1-researcher.conf"


# ###### Run test ###########################################################
if [ -e "${DATABASE_CONFIG}" ] ; then

   if [ ! -e good -o ! -e bad -o ! -e data ] ; then
      echo >&2 "ERROR: Directories missing! Did 5-perform-hpct-importer-test succeed?"
      exit 1
   fi

   for table in Ping Traceroute ; do

      echo "Obtaining ${table} data from good/ directory ..."
      find good/ -name "${table}-*.results.*" | ../hpct-results-tool --input-file-names-from-stdin -o imported-${table,,}.csv

      echo "Querying ${table} data from database ..."
      ../hpct-query "${DATABASE_CONFIG}" ${table,,} -o queried-${table,,}.results
      ../hpct-results-tool queried-${table,,}.results -o queried-${table,,}.csv

      echo "Checking for differences in ${table}:"
      wc -ml imported-${table,,}.csv
      wc -ml queried-${table,,}.csv
      if ! diff imported-${table,,}.csv queried-${table,,}.csv ; then
         echo "RESULTS DIFFER!"
         diff --color=always imported-${table,,}.csv queried-${table,,}.csv | head -n32
         exit 1
      fi

   done

   echo "SUCCESS!"


# ###### Error ##############################################################
else
   echo >&2 "ERROR: ${DATABASE_CONFIG} not found!"
   exit 1
fi
