#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2024 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -o nounset
set -o errexit


if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql [--force-removal-without-confirmation]"
   exit 1
fi

if [ "$2" != "--force-removal-without-confirmation" ] ; then
   echo -n "WARNING: THIS SCRIPT WILL ERASE THE EXISTING DATABASES. To proceed, type \"I am sure!\": "
   read -er agree
   if [ "$agree" != "I am sure!" ] ; then
      echo "Exiting."
      exit
   fi
fi


# ###### MariaDB ############################################################
if [ "$1" == "mariadb" ] ; then
   echo "Uninstalling MariaDB ..."

   sudo DEBIAN_FRONTEND=noninteractive apt purge -y 'mariadb*'
   sudo rm -rf /var/lib/mysql/*
   sudo rmdir /var/lib/mysql || true


# ###### PostgreSQL #########################################################
elif [ "$1" == "postgresql" ] ; then
   echo "Uninstalling PostgreSQL ..."

   sudo DEBIAN_FRONTEND=noninteractive apt purge -y 'postgresql*'
   sudo rm -rf /var/lib/postgresql/*
   sudo rmdir /var/lib/postgresql || true


# ###### MongoDB ############################################################
elif [ "$1" == "mongodb" ] ; then
   echo "Uninstalling MongoDB ..."

   sudo DEBIAN_FRONTEND=noninteractive apt purge -y 'mongodb*'
   sudo rm -rf /var/lib/mongodb/*
   sudo rmdir /var/lib/mongodb || true

# ###### Error ##############################################################
else
   echo >&2 "ERROR: Unsupported database: $1"
   exit 1
fi
