#!/usr/bin/env bash
# ==========================================================================
#     _   _ _ ____            ____          _____
#    | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
#    | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
#    |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
#    |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
#
#       ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
#                 https://www.nntb.no/~dreibh/hipercontracer/
# ==========================================================================
#
# High-Performance Connectivity Tracer (HiPerConTracer)
# Copyright (C) 2015-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -eu

if [ $# -lt 2 ] ; then
   echo >&2 "Usage: $0 ca_certificate certificate ..."
   exit 1
fi
CA="$1"
shift

# ====== Look for CA certificate ============================================
if [ ! -e "${CA}" ] ; then
   echo >&2 "ERROR: Unable to find CA certificate file ${CA}!"
   exit 1
fi

while [ $# -gt 0 ] ; do
   # ====== Look for certificate ============================================
   CERT="$1"
   shift
   if [ ! -e "${CERT}" ] ; then
      echo >&2 "ERROR: Unable to find certificate file ${CERT}!"
      exit 1
   fi

   # ====== Show hierarchy ==================================================
   echo -e "\e[34mHierarchy in ${CERT}:\e[0m"
   openssl crl2pkcs7 -nocrl -certfile "${CERT}" | \
      openssl pkcs7 -print_certs -noout | awk '
BEGIN {
   S=0
}
/^$/       { next }
/^issuer/  { next }
/^subject/ { S++; N=sprintf("%d. ", S); print("\x1b[33m", N $0, "\x1b[0m"); next }
# /^issuer/  { print "\x1b[37m   " $0 "\x1b[0m"; next }
{ print }
'

    # ====== Verify certificate with CA certificate =========================
   echo -e "\e[34mVerifying ${CERT} with CA ${CA}:\e[0m"
   if [ "${CERT}" == "${CA}" ] ; then
      echo "WARNING: Only checking self-signature!"
   fi
   errors=0

   echo -en "\e[33mOpenSSL:\e[0m "
   if openssl verify -CAfile "${CA}" --untrusted "${CERT}" "${CERT}" >/dev/null 2>&1 ; then
      echo "OK"
   else
      errors=$((errors + 1))
      echo "BAD!"
      openssl verify -CAfile "${CA}" --untrusted "${CERT}" "${CERT}" || true
   fi

   echo -en "\e[33mGNU TLS:\e[0m "
   if certtool --verify --load-ca-certificate "${CA}" --infile "${CERT}" >/dev/null 2>&1 ; then
      echo "OK"
   else
      errors=$((errors + 1))
      echo "BAD!"
      certtool --verify --load-ca-certificate "${CA}" --infile "${CERT}" || true
   fi
done
