#!/usr/bin/env bash
# ==========================================================================
#     _   _ _ ____            ____          _____
#    | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
#    | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
#    |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
#    |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
#
#       ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
#                 https://www.nntb.no/~dreibh/hipercontracer/
# ==========================================================================
#
# High-Performance Connectivity Tracer (HiPerConTracer)
# Copyright (C) 2015-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -e


# Copy configuration from dbtest VM:
if [ $# -ne 1 ] ; then
   echo >&2 "Usage: $0 user@server"
   exit 1
fi
SERVER="${1//*@/}"
USER="${1//@*/}"
if [ "${USER}" == "${SERVER}" ] ; then
   USER="nornetpp"
fi


echo -e "\x1b[34mCopying database access configuration from test server ...\x1b[0m"

rsync -v "${USER}@${SERVER}":*.{conf,crt,crl,pem} "${HOME}/" || true

# -e "s/^\(dbserver[ \t]*\)=.*\$/\1= ${SERVER}/g"
sed -e "s#^\(dbcafile[ \t]*\)=[[:space:]]*/home/${USER}/\(.*\)#\1= ${HOME}/\2#g" \
    -e "s#^\(dbcrlfile[ \t]*\)=[[:space:]]*/home/${USER}/\(.*\)#\1= ${HOME}/\2#g" \
    -i "${HOME}"/*.conf

echo -e "\x1b[34mDone!\x1b[0m"
