#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# X.509 Tools
# Copyright (C) 2025-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -euo pipefail


DIRNAME="$(dirname "$0")"

# Generate a client certificate for the local machine (hostname as FQDN):
"${DIRNAME}/generate-test-certificates" TestCA --client --san LOCAL "$(hostname -f)"

# Generate some test server certificates:
# NOTE: These lines must contain resolvable (/etc/hosts or DNS) hostnames:
# "${DIRNAME}/generate-test-certificates" TestCA --server --san LOOKUP besserud.proxmox.crnalab.net
# "${DIRNAME}/generate-test-certificates" TestCA --server --san LOOKUP lillevann.proxmox.crnalab.net
# "${DIRNAME}/generate-test-certificates" TestCA --server --san LOOKUP midtstuen.proxmox.crnalab.net

# Generate some test server certificates:
"${DIRNAME}/generate-test-certificates" TestCA --server sognsvann.company.example
"${DIRNAME}/generate-test-certificates" TestCA --server svartkulp.company.example
"${DIRNAME}/generate-test-certificates" TestCA --server maridalsvannet.company.example
"${DIRNAME}/generate-test-certificates" TestCA --server blanksjoe.company.example
"${DIRNAME}/generate-test-certificates" TestCA --server tryvann.company.example
"${DIRNAME}/generate-test-certificates" TestCA --server aaklungen.company.example

# Generate some test user certificates:
"${DIRNAME}/generate-test-certificates" TestCA --user "Dr. Al Bundy <al.bundy@company.example>"
"${DIRNAME}/generate-test-certificates" TestCA --user "James Bond <james.bond@company.example>"
