#!/usr/bin/env bash
# ==========================================================================
#     _   _ _ ____            ____          _____
#    | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
#    | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
#    |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
#    |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
#
#       ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
#                 https://www.nntb.no/~dreibh/hipercontracer/
# ==========================================================================
#
# High-Performance Connectivity Tracer (HiPerConTracer)
# Copyright (C) 2015-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -eu


if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 name ..."
   exit 1
fi
HEADER="# Testbed:"
if ! grep -q "^${HEADER}" /etc/hosts ; then
   cat >>/etc/hosts <<EOF

${HEADER}
EOF
fi

while [ $# -gt 0 ] ;do
   NAME="$1"
   shift
   name="$(echo "${NAME}" | sed -e "s/\..*$//g")"
   domain="$(echo "${NAME}" | sed -e "s/^[^\.]*\.//g")"
   echo "${name}.${domain}"
   sed \
      -e "/${name}\.${domain}/d" \
      -e "s/^\(${HEADER}.*\)$/\1\n127.0.0.1 ${name}.${domain} ${name}\n::1       ${name}.${domain} ${name}/" \
      </etc/hosts >/etc/hosts.new && \
   mv /etc/hosts.new /etc/hosts
done
