#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2024 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -o nounset
set -o errexit


if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 name ..."
   exit 1
fi
HEADER="# Testbed:"
if ! grep -q "^${HEADER}" /etc/hosts ; then
   cat >>/etc/hosts <<EOF

${HEADER}
EOF
fi

while [ $# -gt 0 ] ;do
   NAME="$1"
   shift
   name="$(echo "${NAME}" | sed -e "s/\..*$//g")"
   domain="$(echo "${NAME}" | sed -e "s/^[^\.]*\.//g")"
   echo "${name}.${domain}"
   sed \
      -e "/${name}\.${domain}/d" \
      -e "s/^\(${HEADER}.*\)$/\1\n127.0.0.1 ${name}.${domain} ${name}\n::1       ${name}.${domain} ${name}/" \
      </etc/hosts >/etc/hosts.new && \
   mv /etc/hosts.new /etc/hosts
done
