#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2024 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -e

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 ALL|mariadb|mongodb|mysql|postgresql [--memcheck|--helgrind]"
   exit 1
fi

HOSTNAME=$(hostname -s)
if [ "${HOSTNAME}" != "localhost" ] && [ "${HOSTNAME}" != "dbtest" ] && [ "${HOSTNAME}" != "midtstuen" ] ; then
   echo >&2 "Hostname is not \"localhost\" or \"dbtest\". This script assumes to be run on a TEST SYSTEM only, since it replaces (i.e. erases) existing installations of PostgreSQL, MariaDB/MySQL and MongoDB!"
   echo >&2 "Stopping here."
   exit 1
fi

if [ "$1" == "ALL" ] ; then
   $0 mariadb    "$2"
   $0 postgresql "$2"
   $0 mongodb    "$2"
   exit 0
fi

if [ $# -gt 1 ] ; then
   if [ "$2" == "--memcheck" ] ; then
      export VALGRIND_CMD="valgrind --tool=memcheck --leak-check=full"
   elif [ "$2" == "--helgrind" ] ; then
      export VALGRIND_CMD="valgrind --tool=helgrind"
   else
      echo >&2 "ERROR: Unknown option $2!"
      exit 1
   fi
else
   export VALGRIND_CMD=
fi



USERS_CONFIG=~/testdb-users.conf

./0-make-configurations     ${USERS_CONFIG}

# Uninstall existing DBMS first:
./9-uninstall-database      "$1" --force-removal-without-confirmation

# Install the DBMS and configure it:
./1-install-database        "$1" ${USERS_CONFIG}
./2-initialise-database     "$1" ${USERS_CONFIG} --force-removal-without-confirmation
./3-test-database           "$1" ${USERS_CONFIG}

# Run importer test:
./4-clean-database          "$1" ${USERS_CONFIG} --force-removal-without-confirmation
# shellcheck disable=SC2211
./5-perform-*-importer-test "$1"
./3-test-database           "$1" ${USERS_CONFIG}
# shellcheck disable=SC2211
./6-perform-*-query-test    "$1"


echo -e '\x1b[42m*** TEST SUCCESSFULLY FINISHED! ***\x1b[0m'
