#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2022 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -e

if [ $# -ne 1 ] ; then
   echo >&2 "Usage: $0 mariadb|mongodb|mysql|postgresql"
   exit 1
fi

HOSTNAME=`hostname -s`
if [ "${HOSTNAME}" != "localhost" -a \
     "${HOSTNAME}" != "dbtest"    -a \
     "${HOSTNAME}" != "midtstuen" ] ; then
   echo >&2 "Hostname is not \"localhost\" or \"dbtest\". This script assumes to be run on a TEST SYSTEM only, since it replaces (i.e. erases) existing installations of PostgreSQL, MariaDB/MySQL and MongoDB!"
   echo >&2 "Stopping here."
   exit 1
fi


USERS_CONFIG=~/testdb-users.conf

./0-make-users.conf     ${USERS_CONFIG}

# Uninstall existing DBMS first:
./4-uninstall-database  $1 --force-removal-without-confirmation 

# Install the DBMS and configure it:
./1-install-database    $1 ${USERS_CONFIG}
./2-initialise-database $1 ${USERS_CONFIG} --force-removal-without-confirmation
./3-test-database       $1 ${USERS_CONFIG}
