#!/bin/bash

if [ $# -ne 2 ] ; then
   echo >&2 "Usage: $0 host:port cafile"
   exit 1
fi
ENDPOINT="$1"
CAFILE="$2"
if [ ! -e "${CAFILE}" ] ; then
   echo >&2 "ERROR: ${CAFILE} does not exist!"
   exit 1
fi

echo "" | openssl s_client -showcerts -connect ${ENDPOINT}  -CAfile "${CAFILE}" | head
