#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# X.509 Certificate Viewer
# Copyright (C) 2025-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -euo pipefail

# gettext options:
export TEXTDOMAIN="view-certificate"
# export TEXTDOMAINDIR="${PWD}/locale"   # Default: "/usr/share/locale"

# shellcheck disable=SC1091
. gettext.sh


# ###### Usage ##############################################################
usage () {
   local exitCode="$1"
   echo >&2 "$(gettext "Usage:") $0 [-h|--help] [-v|--version] certificate [...]"
   exit "${exitCode}"
}


# ###### Version ############################################################
version () {
   echo "view-certificate 2.6.1"
   exit 0
}


# ###### Print date in current locale and current time zone #################
print-date ()
{
   local input="$1"
   local unixTS
   local datetime
   if date --version >/dev/null 2>&1; then
      unixTS="$(date -d "${input}" +"%s")"
      datetime="$(date -d "@${unixTS}" +"%c %Z")"
   else
      unixTS="$(LC_ALL=C.UTF-8 date -j -f "%b %d %T %Y %Z" "${input}" +"%s")"
      datetime="$(date -r "${unixTS}" +"%c %Z")"
   fi
   echo "${datetime}"
}



# ###### Main program #######################################################

# ====== Handle arguments ===================================================
if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
   exit 1
fi
GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
   exit 1
fi
options="$(${GETOPT} -o hv --long help,version -a -- "$@")"
# shellcheck disable=SC2181
if [[ $? -ne 0 ]]; then
   usage 1
fi
eval set -- "${options}"

while [ $# -gt 0 ] ; do
   case "$1" in
      -h | --help)
         usage 0
         ;;
      -v | --version)
         version
         ;;
      --)
         shift
         break
         ;;
      *)
         # This should not happen: wrong getopt parameters, or missing case?
         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
         exit 1
         ;;
  esac
  shift
done
if [ $# -lt 1 ] ; then
   usage 1
fi

# ====== Check availability of tools ========================================
OPENSSL="$(command -v openssl || true)"
if [ "${OPENSSL}" == "" ] ; then
   gettext >&2 "ERROR: OpenSSL is not installed!"
   echo >&2
   exit 1
fi

# ====== Prepare labels and compute indentation =============================
declare -A labels=(
   ["Subject"]="$(gettext "Subject:")"
   ["Subject Alternative Name"]="$(gettext "Subject Alternative Name:")"
   ["Validity"]="$(gettext "Validity:")"
   ["Basic Constraints"]="$(gettext "Basic Constraints:")"
   ["Key Usage"]="$(gettext "Key Usage:")"
   ["Extended Key Usage"]="$(gettext "Extended Key Usage:")"
   ["Subject Key Identifier"]="$(gettext "Subject Key Identifier:")"
   ["Authority Key Identifier"]="$(gettext "Authority Key Identifier:")"
)

indent=0
for label in "${!labels[@]}" ; do
   width="$(print-utf8 --width "${label}")"
   if [ "${width}" -gt "${indent}" ] ; then
      indent="${width}"
   fi
done
indent=-$((indent + 2))

# ====== Check each certificate =============================================
while [ $# -gt 0 ] ; do

   # ====== Look for certificate ============================================
   CERTIFICATE_FILE="$1"
   shift
   if [ "${CERTIFICATE_FILE}" == "-" ] ; then
      CERTIFICATE_FILE="/dev/stdin"
   fi
   if [ ! -e "${CERTIFICATE_FILE}" ] ; then
      eval_gettext >&2 "ERROR: Unable to find certificate file \${CERTIFICATE_FILE}!"
      echo >&2
      exit 1
   fi

   echo -e "\e[34m$(eval_gettext "Certificate in \${CERTIFICATE_FILE}:")\e[0m"
   "${OPENSSL}" x509 -in "${CERTIFICATE_FILE}" -noout -subject -dates -ext subjectAltName,basicConstraints,keyUsage,extendedKeyUsage,subjectKeyIdentifier,authorityKeyIdentifier | (
      # ====== Extract certificate details ==================================
      validityFrom="?"
      validityTo="?"
      subject="?"
      declare -A extensionValues=(
         ["Subject Alternative Name"]="(none)"
         ["Key Usage"]="(none)"
         ["Basic Constraints"]="(none)"
         ["Extended Key Usage"]="(none)"
         ["Subject Key Identifier"]="(none)"
         ["Authority Key Identifier"]="(none)"
      )
      while read -r line ; do
         if [[ "${line}" =~ ^(subject=)(.*)$ ]] ; then
            # Subject with underlined CN:
            # shellcheck disable=SC2001
            subject="$(sed -e 's|\(CN = [^,]*\)|\x1b[4m\1\x1b[24m|' <<< "${BASH_REMATCH[2]}")"
         elif [[ "${line}" =~ ^(notBefore=)(.*)$ ]] ; then
            validityFrom="$(print-date "${BASH_REMATCH[2]}")"
         elif [[ "${line}" =~ ^(notAfter=)(.*)$ ]] ; then
            validityTo="$(print-date "${BASH_REMATCH[2]}")"
         elif [[ "${line}" =~ ^([ \t]*)(X509v3 )(.*)(:[[:space:]]*)(.*)$ ]] ; then
            extension="${BASH_REMATCH[3]}"
            critical="${BASH_REMATCH[5]}"
            if [ "${critical}" != "" ] ; then
               extensionValues["${extension}"]="\\e[4m${critical}:\\e[24m "
            else
               extensionValues["${extension}"]=""
            fi
         elif [ "${extension}" != "" ] && [[ "${line}" =~ ^([[:space:]]*)(.*)$ ]] ; then
            extensionValues["${extension}"]+="${BASH_REMATCH[2]}"
            extension=""
         fi
      done

      # ====== Display certificate details ==================================
      print-utf8 -i "${indent}" "\e[33m${labels["Subject"]}"
      echo -e "\e[35m${subject}\e[0m"
      print-utf8 -i "${indent}" "\e[33m${labels["Subject Alternative Name"]}"
      echo -e "\e[35m${extensionValues["Subject Alternative Name"]}\e[0m"
      print-utf8 -i "${indent}" "\e[33m${labels["Validity"]}"
      echo -e "\e[36m${validityFrom}\e[33m — \e[36m${validityTo}\e[0m"
      for extension in "Basic Constraints"      \
                       "Key Usage"              \
                       "Extended Key Usage"     \
                       "Subject Key Identifier" \
                       "Authority Key Identifier" ; do
         print-utf8 -i "${indent}" "\e[33m${labels["${extension}"]}"
         echo -e "${extensionValues["${extension}"]}\e[0m"
      done
   )
   echo -en "\e[0m"

   # ====== Display certificate hierarchy ===================================
   echo -e "\e[34m$(eval_gettext "Hierarchy in \${CERTIFICATE_FILE}:")\e[0m"
   "${OPENSSL}" crl2pkcs7 -nocrl -certfile "${CERTIFICATE_FILE}" | \
      "${OPENSSL}" pkcs7 -print_certs -noout | (
         entry=0
         while read -r line ; do
            if [[ "${line}" =~ ^(subject=)(.*)$ ]] ; then
               # Subject with underlined CN:
               # shellcheck disable=SC2001
               subject="$(sed -e 's|\(CN = [^,]*\)|\x1b[4m\1\x1b[24m|' <<< "${BASH_REMATCH[2]}")"

               entry=$((entry + 1))
               echo -en " \x1b[33m$(eval_gettext "#\${entry}.") "
               if [ ${entry} -eq 1 ] ; then
                  echo -e "\e[35m${subject}\e[0m"
               else
                  echo -e "\e[37m${subject}\e[0m"
               fi
            fi
         done
      )

done
