#!/usr/bin/env python3
# ==========================================================================
#     _   _ _ ____            ____          _____
#    | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
#    | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
#    |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
#    |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
#
#       ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
#                 https://www.nntb.no/~dreibh/hipercontracer/
# ==========================================================================
#
# High-Performance Connectivity Tracer (HiPerConTracer)
# Copyright (C) 2015-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

import ipaddress
import os
import sys
import time
import typing
import signal
import subprocess


# ###########################################################################
# #### HiPerConTracer Measurement                                        ####
# ###########################################################################

class HiPerConTracerMeasurement:

   # ###### Constructor #####################################################
   def __init__(
      self,
      measurementID:    int,
      services:         list[str],
      modules:          list[str],
      sources:          list[ipaddress.ip_address],
      destinations:     list[ipaddress.ip_address],
      resultsDirectory: str,
      resultsTrLength:  int,
      details:          dict = { },
      logFile:          str  = None,
      sudoNeeded:       bool = False) -> None:

      # ====== Initialise main parameters ===================================
      self.MeasurementID    = measurementID
      self.Services         = services
      self.Modules          = modules
      self.Sources          = sources
      self.Destinations     = destinations
      self.ResultsDirectory = resultsDirectory
      self.ResultsTrLength  = resultsTrLength
      self.Details          = details
      self.LogFile          = logFile

      # ====== Create command ===============================================
      if sudoNeeded:
         self.Command = [ 'sudo', 'hipercontracer' ]
      else:
         self.Command = [ 'hipercontracer' ]
      for service in self.Services:
         if service == 'Ping':
            self.Command.append('--ping')
         elif service == 'Traceroute':
            self.Command.append('--traceroute')
         elif service == 'Jitter':
            self.Command.append('--jitter')
         else:
            raise Exception('Invalid service: ' + service)
      self.Command.append('--resultsdirectory')
      self.Command.append(self.ResultsDirectory)
      self.Command.append('--resultstransactionlength')
      self.Command.append(str(self.ResultsTrLength))
      if self.LogFile:
         self.Command.append('--logfile')
         self.Command.append(self.LogFile)
      for module in self.Modules:
         self.Command.append('--iomodule')
         self.Command.append(str(module))
      for source in self.Sources:
         self.Command.append('--source')
         self.Command.append(str(source))
      for destination in self.Destinations:
         self.Command.append('--destination')
         self.Command.append(str(destination))

      # ====== Add custom parameters ========================================
      for key, value in self.Details.items():
         self.Command.append('--' + key)
         self.Command.append(str(value))

      self.Process = None
      print(self.Command)


   # ###### Start process ###################################################
   def start(self) -> None:
      if self.Process:
         raise Exception('Process already exists!')
      self.Process = subprocess.Popen(self.Command, stdin = None)


   # ###### Stop process ####################################################
   def stop(self, timeout = 10) -> None:
      if self.Process:
         # Send SIGINT, to gracefully shut down HiPerConTracer
         self.Process.send_signal(signal.SIGINT)
         if not self.Process.wait(timeout):
            # Something seems to be wrong -> send SIGKILL to terminate it!
            self.Process.send_signal(signal.SIGKILL)
         self.Process = None


   # ###### Check process status ############################################
   def check(self) -> bool:
      if not self.Process:
         return False
      return (self.Process.poll() == None)



# ###### Main program #######################################################
h = HiPerConTracerMeasurement(12345678, [ 'Ping' ], [ 'ICMP', 'UDP' ],
                              [ ipaddress.ip_address('0.0.0.0') ],
                              [ ipaddress.ip_address('8.8.8.8') ],
                              'data', 300,
                              { 'pingudpdestinationport':       7,
                                'tracerouteudpdestinationport': 7 },
                              'hpct.log', True)
h.start()

for i in range(1,20):

   time.sleep(1)
   running = h.check()

   if running:
      sys.stdout.write('Still running...\n')
   else:
      sys.stdout.write('Stopped!\n')
      break

   if i == 8:
      h.stop()
