#!/usr/bin/env python3

import HiPerConTracer

t0 = 1788258897516035018
print(t0)

s = HiPerConTracer.unixtime_to_string(t0)
print(s)
t = HiPerConTracer.string_to_unixtime(s)
print(t)

assert (t == t0)
