#!/usr/bin/bash
# ==========================================================================
#     _   _ _ ____            ____          _____
#    | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
#    | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
#    |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
#    |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
#
#       ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
#                 https://www.nntb.no/~dreibh/hipercontracer/
# ==========================================================================
#
# High-Performance Connectivity Tracer (HiPerConTracer)
# Copyright (C) 2015-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -eu


INPUTS="test.hpct"
LEVELS="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19"
ROUNDS="0"

declare -A COMPRESSORS=(
   ["gzip"]="GZip"
   ["pigz"]="Parallel GZip"
   ["bzip2"]="BZip2"
   ["pbzip2"]="Parallel BZip2"
   ["xz"]="XZ"
   ["zlib-flate"]="ZLib-Flate"
   ["lzma"]="LZMA"
   ["zstd"]="ZStandard"
)

declare -A EXTENSIONS=(
   ["gzip"]="gz"
   ["pigz"]="gz"
   ["bzip2"]="bz2"
   ["pbzip2"]="bz2"
   ["xz"]="xz"
   ["zlib-flate"]="zz"
   ["lzma"]="lzma"
   ["zstd"]="zst"
)


# ====== Checks =============================================================
check-program ()
{
   local name="$1"
   if ! which "${name}" >/dev/null 2>&1 ; then
      echo "ERROR: ${name} is not installed!"
      exit 1
   fi
}

check-program gzip
check-program pigz
check-program bzip2
check-program pbzip2
check-program xz
check-program lzma
check-program zlib-flate
check-program zstd


# ====== Run tests ==========================================================
echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Running measurements\x1b[0m"
for round in ${ROUNDS} ; do
   mkdir -p "${round}"
   for input in ${INPUTS} ; do
      for level in ${LEVELS} ; do
         echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Running measurements: round ${round}, level ${level}, input ${input}\x1b[0m"
         if [ "${level}" -le 9 ] ; then
            if [ ! -e "${round}/${input}.xz.${level}.xz" ] ; then
               /bin/time -p -o "${round}/${input}.xz.${level}.xz.time" \
                  xz -T 0 -"${level}" -c "${input}" >"${round}/${input}.xz.${level}.xz.tmp" && \
                  mv "${round}/${input}.xz.${level}.xz.tmp" "${round}/${input}.xz.${level}.xz"
            fi
            if [ "${level}" -gt 0 ] ; then
               if [ ! -e "${round}/${input}.gzip.${level}.gz" ] ; then
                  /bin/time -p -o "${round}/${input}.gzip.${level}.gz.time" \
                     gzip -"${level}" -c "${input}" >"${round}/${input}.gzip.${level}.gz.tmp" && \
                     mv "${round}/${input}.gzip.${level}.gz.tmp" "${round}/${input}.gzip.${level}.gz"
               fi
               if [ ! -e "${round}/${input}.pigz.${level}.gz" ] ; then
                  /bin/time -p -o "${round}/${input}.pigz.${level}.gz.time" \
                     pigz -"${level}" -c "${input}" >"${round}/${input}.pigz.${level}.gz.tmp" && \
                     mv "${round}/${input}.pigz.${level}.gz.tmp" "${round}/${input}.pigz.${level}.gz"
               fi
               if [ ! -e "${round}/${input}.bzip2.${level}.bz2" ] ; then
                  /bin/time -p -o "${round}/${input}.bzip2.${level}.bz2.time" \
                     bzip2 -"${level}" -c "${input}" >"${round}/${input}.bzip2.${level}.bz2.tmp" && \
                     mv "${round}/${input}.bzip2.${level}.bz2.tmp" "${round}/${input}.bzip2.${level}.bz2"
               fi
               if [ ! -e "${round}/${input}.pbzip2.${level}.bz2" ] ; then
                  /bin/time -p -o "${round}/${input}.pbzip2.${level}.bz2.time" \
                     pbzip2 -"${level}" -c "${input}" >"${round}/${input}.pbzip2.${level}.bz2.tmp" && \
                     mv "${round}/${input}.pbzip2.${level}.bz2.tmp" "${round}/${input}.pbzip2.${level}.bz2"
               fi
               if [ ! -e "${round}/${input}.zlib-flate.${level}.zz" ] ; then
                  /bin/time -p -o "${round}/${input}.zlib-flate.${level}.zz.time" \
                     zlib-flate -compress="${level}" <"${input}" >"${round}/${input}.zlib-flate.${level}.zz.tmp" && \
                     mv "${round}/${input}.zlib-flate.${level}.zz.tmp" "${round}/${input}.zlib-flate.${level}.zz"
               fi
               if [ ! -e "${round}/${input}.lzma.${level}.lzma" ] ; then
                  /bin/time -p -o "${round}/${input}.lzma.${level}.lzma.time" \
                     lzma -T 0 -"${level}" -c "${input}" >"${round}/${input}.lzma.${level}.lzma.tmp" && \
                     mv "${round}/${input}.lzma.${level}.lzma.tmp" "${round}/${input}.lzma.${level}.lzma"
               fi
            fi
         fi
         if [ ! -e "${round}/${input}.zstd.${level}.zst" ] ; then
            /bin/time -p -o "${round}/${input}.zstd.${level}.zst.time" \
               zstd -T0 -"${level}" "${input}" -kfq -o "${round}/${input}.zstd.${level}.zst.tmp" && \
               mv "${round}/${input}.zstd.${level}.zst.tmp" "${round}/${input}.zstd.${level}.zst"
         fi
      done
   done
done


# ====== Collect results ====================================================
echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Collecting results\x1b[0m"
(
   echo "Round Input OriginalSize Program Compressor Extension Level Size Real User Sys"
   originalSize="$(wc -c "${input}" | cut -d' ' -f1)"
   for round in ${ROUNDS} ; do
      for input in ${INPUTS} ; do
         for level in ${LEVELS} ; do
            for program in "${!COMPRESSORS[@]}" ; do
               compressor="${COMPRESSORS[${program}]}"
               extension="${EXTENSIONS[${program}]}"
               if [ -e "${round}/${input}.${program}.${level}.${extension}" ] && [ -e "${round}/${input}.${program}.${level}.${extension}.time" ] ; then
                  size="$(wc -c "${round}/${input}.${program}.${level}.${extension}" | cut -d' ' -f1)"
                  real="$(grep "^real" "${round}/${input}.${program}.${level}.${extension}.time" | cut -d' ' -f2)"
                  user="$(grep "^user" "${round}/${input}.${program}.${level}.${extension}.time" | cut -d' ' -f2)"
                  sys="$(grep "^sys"   "${round}/${input}.${program}.${level}.${extension}.time" | cut -d' ' -f2)"
                  echo "${round} ${input} $originalSize \"${program}\" \"${compressor}\" \"${extension}\" ${level} ${size} ${real} ${user} ${sys}"
               else
                echo >&2 "N/A: ${round}/${input}.${program}.${level}.${extension}   ${round}/${input}.${program}.${level}.${extension}.time"
               fi
            done
         done
      done
   done
) | tee results.data

echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Done!\x1b[0m"
