#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2024 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -e


# ====== Handle arguments ===================================================
if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 configuration_file [-d|--dry-run] [-q|--quiet] [-B|--write-dbeaver-config file_prefix]"
   exit 1
fi
CONFIGURATION_FILE="$1"
shift
if [ ! -e "${CONFIGURATION_FILE}" ] ; then
   echo >&2 "ERROR: Use configuration ${CONFIGURATION_FILE} does not exist!"
fi
DRY_RUN=0
QUIET=0
DBEAVER_CONFIG_PREFIX=""
while [ $# -gt 0 ] ; do
   if [ "$1" == "-d" ] || [ "$1" == "--dry-run" ] ; then
      DRY_RUN=1
   elif [ "$1" == "-q" ] || [ "$1" == "--quiet" ] ; then
      QUIET=1
   elif [ "$1" == "-B" ] || [ "$1" == "--get-dbeaver-config" ] ; then
      DBEAVER_CONFIG_PREFIX="$2"
      shift
   else
      echo >&2 "ERROR: Invalid argument $1!"
      exit 1
   fi
   shift
done


# ====== Read configuration file ============================================
dbbackend=""
dbserver=""
dbport=""
dbuser=""
dbpassword=""
database=""
dbcafile=""
dbcrlfile=""
configContent=$(sed -r '/[^=#]+=[^=]+/!d' <"${CONFIGURATION_FILE}" | sed -r "s/[[:space:]]*=[[:space:]]*(.*)[[:space:]]*/='\1'/g")
eval "${configContent}"
if [ "${dbcafile}" == "NONE" ] ; then
   dbcafile=""
fi
if [ "${dbcrlfile}" == "NONE" ] ; then
   dbcrlfile=""
fi
if [ "${dbkeyfile}" == "NONE" ] ; then
   dbkeyfile=""
fi
if [ "${dbcertfile}" == "NONE" ] ; then
   dbcertfile=""
fi


# ====== Build the parameters line =============================================
oldCommand=0
command=""
parameters=""
if [ "${dbbackend}" == "MariaDB" ] || [ "${dbbackend}" == "MySQL" ] ; then

   if [ "${dbbackend}" == "MariaDB" ] ; then
      command="$(which mariadb || true)"
      if [ "${command}" == "" ] ; then
         command="mariadb"
      fi
   else
      command="$(which mysql || true)"
      if [ "${command}" == "" ] ; then
         command="mysql"
      fi
   fi
   if [ "${dbport}" == "0" ] ; then
      dbport="3306"
   fi
   export MYSQL_PWD="${dbpassword}"
   parameters="${parameters} --host=\"${dbserver}\" --port=${dbport} --protocol=tcp --user=\"${dbuser}\" --database=\"${database}\""
   if [ "${dbcafile}" != "" ] ; then
      parameters="${parameters} --ssl-verify-server-cert --ssl-ca=\"${dbcafile}\" --ssl-crl=\"${dbcafile}\""
      if [ "${dbcrlfile}" != "" ] ; then
         parameters="${parameters} --ssl-crl \"${dbcrlfile}\""
      fi
   fi

elif [ "${dbbackend}" == "PostgreSQL" ] ; then

   command="$(which psql || true)"
   if [ "${command}" == "" ] ; then
      command="psql"
   fi
   if [ "${dbport}" == "0" ] ; then
      dbport="5432"
   fi
   parameters="--host=\"${dbserver}\" --port=${dbport} --username=\"${dbuser}\" --dbname=\"${database}\""
   export PGPASSWORD="${dbpassword}"
   if [ "${dbcafile}" != "" ] ; then
      export PGSSLMODE="verify-full"
      export PGSSLROOTCERT="${dbcafile}"
      if [ "${dbcrlfile}" != "" ] ; then
         export PGSSLCRL="${dbcrlfile}"
      fi
   fi

elif [ "${dbbackend}" == "MongoDB" ] ; then

   command="$(which mongosh || true)"
   if [ "${command}" == "" ] ; then
      command="$(which mongo || true)"
      if [ "${command}" == "" ] ; then
         command="mongosh"
      else
         oldCommand=1
      fi
   fi
   if [ "${dbport}" == "0" ] ; then
      dbport="27017"
   fi
   parameters="\"mongodb://${dbserver}:${dbport}/${database}\" --username \"${dbuser}\" --password \"${dbpassword}\""
   if [ "${dbcafile}" != "" ] ; then
      if [ ${oldCommand} -eq 0 ] ; then
         parameters="${parameters} --tls --tlsDisabledProtocols TLS1_0,TLS1_1,TLS1_2 --tlsCAFile \"${dbcafile}\""
         if [ "${dbcrlfile}" != "" ] ; then
            # FIXME: --tlsCRLFile \"${dbcrlfile}\" does not work!
            # parameters="${parameters} --tlsCRLFile \"${dbcrlfile}\""
            true
         fi
      else
         parameters="${parameters} --ssl --sslDisabledProtocols TLS1_0,TLS1_1,TLS1_2 --sslCAFile \"${dbcafile}\""
         if [ "${dbcrlfile}" != "" ] ; then
            parameters="${parameters} --sslCRLFile \"${dbcrlfile}\""
         fi
      fi
   fi

else

   echo >&2 "ERROR: Invalid dbbackend setting \"${dbbackend}!\""
   exit 1

fi


# ====== Generate DBeaver configuration file ================================
if [ "${DBEAVER_CONFIG_PREFIX}" ] ; then
   driver=""
   provider=""
   custom=""
   dbusername="${dbuser}"
   if [ "${dbbackend}" == "MariaDB" ] || [ "${dbbackend}" == "MySQL" ] ; then
      driver="mysql8"
      provider="mysql"
      handler="mysql_ssl"
      custom=",
							\"ssl.require\": \"true\",
							\"ssl.verify.server\": \"true\",
							\"ssl.public.key.retrieve\": \"false\""
   elif [ "${dbbackend}" == "PostgreSQL" ] ; then
      driver="postgres-jdbc"
      provider="postgresql"
      custom=",
							\"sslMode\": \"verify-full\",
							\"sslFactory\": \"\""
      if [ "${dbuser}" == "postgres" ] ; then
         dbusername="root"
      fi
   else
      if [ ${QUIET} -eq 0 ] ; then
         echo >&2 "WARNING: DBeaver does not support ${dbbackend} backend!"
      fi
      echo "" >"${DBEAVER_CONFIG_PREFIX}-data-source.json"
      echo "" >"${DBEAVER_CONFIG_PREFIX}-credentials-config.json"
   fi
   if [ "${driver}" != "" ] ; then
      color="211,215,207"
      if [ "${dbusername}" == "importer" ] ; then
         color="237,212,0"
      elif [ "${dbusername}" == "researcher" ] ; then
         color="org.jkiss.dbeaver.color.connectionType.qa.background"
      elif [ "${dbusername}" == "maintainer" ] ; then
         color="114,159,207"
      elif [ "${dbusername}" == "root" ] ; then
         color="239,41,41"
      fi
      if [ ${QUIET} -eq 0 ] ; then
         echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Writing DBeaver configuration to ${DBEAVER_CONFIG_PREFIX} ...\x1b[0m"
      fi
      identifier="$(echo "${provider}://${dbusername}@${dbserver}:${dbport}/${database}" | md5sum --tag |  cut -d' ' -f4)"
      (
         cat << EOF
{
	"folders": {},
	"connection-types": {
		"${dbusername}": {
			"name": "${dbusername}",
			"color": "${color}",
			"description": "Regular database access for ${dbusername}",
			"auto-commit": true,
			"confirm-execute": false,
			"confirm-data-change": false,
			"smart-commit": false,
			"smart-commit-recover": true,
			"auto-close-transactions": true,
			"close-transactions-period": 1800,
			"auto-close-connections": true,
			"close-connections-period": 14400
		}
	},
	"connections": {
		"${driver}-${identifier}": {
			"provider": "${provider}",
			"driver": "${driver}",
			"name": "${dbusername}@${dbserver}:${dbport}/${database} ${dbbackend}",
			"save-password": true,
			"configuration": {
				"host": "${dbserver}",
				"port": "${dbport}",
				"database": "${database}",
				"url": "jdbc:${provider}://${dbserver}:${dbport}/${database}",
				"configurationType": "MANUAL",
				"type": "${dbusername}",
				"closeIdleConnection": true,
				"auth-model": "native",
				"handlers": {
					"mysql_ssl": {
						"type": "CONFIG",
						"enabled": true,
						"save-password": true,
						"properties": {
							"ssl.ca.cert": "${dbcafile}",
							"ssl.client.cert": "${dbcertfile}",
							"ssl.client.key": "${dbkeyfile}",
							"ssl.method": "CERTIFICATES",
							"ssl.require": "true",
							"ssl.verify.server": "true",
							"ssl.public.key.retrieve": "false",
							"ssl.cipher.suites": ""${custom}
						}
					}
				}
			}
		}
	}
}
EOF
      ) >"${DBEAVER_CONFIG_PREFIX}-data-source.json"

      (
         cat << EOF
{
	"${driver}-${identifier}": {
		"#connection": {
			"user": "${dbuser}",
			"password": "${dbpassword}"
		}
	}
}
EOF
      ) >"${DBEAVER_CONFIG_PREFIX}-credentials-config.json"
   fi
fi


# ====== Run the parameters line ============================================
if [ ${QUIET} -eq 0 ] ; then
   if [ ${DRY_RUN} -eq 0 ] ; then
      echo -e "\x1b[34m$(date +"%F %H:%M:%S"): Connecting to database ...\x1b[0m"
      echo -en "\x1b[37m"
   fi

   if [ "${dbbackend}" == "MariaDB" ] || [ "${dbbackend}" == "MySQL" ] || [ "${dbbackend}" == "PostgreSQL" ] ; then
      export | grep "MYSQL_PWD=\|PGPASSWORD=\|PGSSL[A-Z]*=" | sort || true
   fi
   echo "${command} ${parameters}"
   fi

if [ ${DRY_RUN} -eq 0 ] ; then
   if [ ${QUIET} -eq 0 ] ; then
      echo -en "\x1b[0m"
   fi
   sh -c "${command} ${parameters}"
fi
