#!/usr/bin/env bash
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2024 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no

# Bash options:
set -eu


if [ $# -ne 2 ] ; then
   echo >&2 "Usage: $0 encrypted_dbeaver_credentials_config_json plain_dbeaver_credentials_config_json"
   exit 1
fi

inputFile="$1"
if [ "${inputFile}" == "-" ] ; then
   inputFile="/dev/stdin"
fi
outputFile="$2"
if [ "${outputFile}" == "-" ] ; then
   outputFile="/dev/stdout"
fi

openssl aes-128-cbc -d \
   -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 \
   -in "${inputFile}" | dd bs=1 skip=16 status=none | jq . >"${outputFile}"
