#!/bin/bash -e
#
#  =================================================================
#           #     #                 #     #
#           ##    #   ####   #####  ##    #  ######   #####
#           # #   #  #    #  #    # # #   #  #          #
#           #  #  #  #    #  #    # #  #  #  #####      #
#           #   # #  #    #  #####  #   # #  #          #
#           #    ##  #    #  #   #  #    ##  #          #
#           #     #   ####   #    # #     #  ######     #
#
#        ---   The NorNet Testbed for Multi-Homed Systems  ---
#                        https://www.nntb.no
#  =================================================================
#
#  High-Performance Connectivity Tracer (HiPerConTracer)
#  Copyright (C) 2015-2019 by Thomas Dreibholz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Contact: dreibh@simula.no


# ###### Find all interfaces with configured default route ##################
INTERFACES_WITH_DEFAULT_ROUTE=`
( /bin/ip -4 route show default ; /bin/ip -6 route show default ) | (
   while read line ; do
      if [[ "${line}" =~ ^(default)([ \t]*)(.*)(dev)([ \t]*)([^[:space:]]*)([ \t]*) ]] ; then
         echo "${BASH_REMATCH[6]}" 
      fi
   done
) | sort -u | xargs
`
# echo "I: ${INTERFACES_WITH_DEFAULT_ROUTE}"


# ###### Get addresses of these interfaces with global scope ################
ADDRESSES_WITH_DEFAULT_ROUTE=`
(
   for interface in ${INTERFACES_WITH_DEFAULT_ROUTE} ; do
      ( ip -4 addr show dev ${interface} scope global ; ip -6 addr show dev ${interface} scope global nodad ) | (
         while read line ; do
            if [[ "${line}" =~ ^([ \t]*)(inet|inet6)([ \t]*)([^[:space:]]*)/ ]] ; then
               echo "${BASH_REMATCH[4]}"
            fi
         done
      )
   done
) | sort -u | xargs
`
# echo "A: ${ADDRESSES_WITH_DEFAULT_ROUTE}"


echo "${ADDRESSES_WITH_DEFAULT_ROUTE}"
