.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2018 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@iem.uni-due.de
.\"
.\" ###### Setup ############################################################
.Dd January 9, 2018
.Dt hipercontracer 1
.Os hipercontracer
.\" ###### Name #############################################################
.Sh NAME
.Nm hipercontracer
.Nd High-Performance Connectivity Tracer (HiPerConTracer)
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm hipercontracer
.Op \-ping
.Op \-traceroute
.Op \-quiet
.Op \-verbose
.Op \-source=address
.Op \-destination=address
.Op \-tracerouteinterval=milliseconds
.Op \-tracerouteduration=milliseconds
.Op \-tracerouterounds=rounds
.Op \-tracerouteinitialmaxttl=value
.Op \-traceroutefinalmaxttl=value
.Op \-tracerouteincrementmaxttl=value
.Op \-pinginterval=milliseconds
.Op \-pingexpiration=milliseconds
.Op \-pingttl=value
.Op \-resultsdirectory=directory
.Op \-resultstransactionlength=seconds
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm hipercontracer
is a ping/traceroute service. It performs regular ping and traceroute runs
among sites and can export the results into results statements for import into
a database.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments may be provided:
.Bl -tag -width indent
.It ping
Start the ping service.
.It traceroute
Start the traceroute service.
.It quiet
Do not print the results to standard output. This is only useful when
exporting into results statement files.
.It verbose
Print the results to standard output.
.It source=address
Adds the given source address.
.It destination=address
Adds the given destination address.
.It tracerouteinterval=milliseconds
Sets the traceroute interval (time for each full round of destinations).
.It tracerouteduration=milliseconds
Sets the traceroute duration (timeout for each destination).
.It -tracerouterounds=rounds
For each traceroute measurement, perform the given number of rounds simultaneously.
Default is 1 round.
Each TTL test of a round will have the same ICMP checksum value ("Oslo Traceroute"),
in order to deal with load balancing in the Internet.
Different rounds will have different checksums. That is, different rounds may
experience different paths in the network.
.It tracerouteinitialmaxttl=value
Start with the given maximum TTL.
.It traceroutefinalmaxttl=value
Finish with the given maximum TTL
(when destination is not reached with current TTL setting).
.It tracerouteincrementmaxttl=value
Increase the maximum TTL by the given value
(when destination is not reached with current TTL setting).
.It pinginterval=milliseconds
Sets the ping interval (time for each full round of destinations).
.It pingexpiration=milliseconds
Sets the ping duration (timeout for each destination).
.It pingttl=value
Sets the ping TTL value.
.It resultsdirectory=directory
Sets the results files directory. The results will be stored there. If not specified, to results will be stored.
.It resultstransactionlength=seconds
After a given number of seconds, begin a new results file.
.El
.\" ###### Output format ####################################################
.Sh OUTPUT FORMAT
The output file is a BZip2-compressed text file. The format is as follows, depending on the measurement type:
.Bl -tag -width indent
.It Ping
Each Ping entry consists of a #P line.
.Bl -tag -width indent
.It #P sourceIP destinationIP timestamp status rtt
.Bl -tag -width indent
.It * sourceIP: Source IP address.
.It * destinationIP: Destination IP address.
.It * timestamp: Timestamp (microseconds since the UTC epoch).
.It * status: Status code (hexadecimal; see "HopStatus" in traceroute.h).
.It * rtt: RTT (milliseconds).
.El
.El
.It Traceroute
Each Traceroute entry begins with a #T line, plus one TAB-started line per hop.
.Bl -tag -width indent
.It #T sourceIP destinationIP timestamp round totalHops statusFlags pathHash
.Bl -tag -width indent
.It * sourceIP: Source IP address.
.It * destinationIP: Destination IP address.
.It * timestamp: Timestamp (microseconds since the UTC epoch).
.It * round: Round number.
.It * totalHops: Total hops.
.It * statusFlags: Status flags (hexadecimal; see "HopStatus" in traceroute.h).
.It * pathHash: Hash of the path (hexadecimal).
.El
.It (TAB) hopNumber status rtt hopIP
.Bl -tag -width indent
.It * hopNumber: Number of the hop.
.It * status: Status code (hexadecimal; see "HopStatus" in traceroute.h).
.It * rtt: RTT (microseconds).
.It * hopIP: Hop IP address (or destination IP, if there was no response).
.El
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It hipercontracer \-source=10.1.1.51 \-destination=10.1.1.6 \-destination=10.1.1.7 \-destination=10.1.1.8 \-traceroute \-tracerouteinterval=10000 \-tracerouteduration=1000
.It hipercontracer \-source=172.16.0.127 \-destination=8.8.8.8 \-destination=193.99.144.80 \-destination=132.252.181.87 \-destination=10.254.254.254 \-destination=91.189.93.5 \-destination=128.112.139.90 \-destination=4.31.198.44 \-destination=136.186.1.10 \-destination=101.4.112.170 \-destination=77.36.144.2 \-source=2a02:270:2014:40:92e2:baff:fe48:bde1 \-destination=2400:cb00:2048:1::6814:155 \-destination=2a02:2e0:3fe:1001:7777:772e:2:85 \-destination=2a00:1450:400f:805::2004 \-traceroute \-ping \-tracerouteduration=1000 \-tracerouteinitialmaxttl=4 \-traceroutefinalmaxttl=32 \-tracerouteincrementmaxttl=4 \-pinginterval=1000 \-pingexpiration=7500 \-pingttl=56 \-resultsdirectory=results
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.uni-due.de/~be0001/hipercontracer
.br
mailto://dreibh@iem.uni-due.de
.br
