.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2021 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@iem.uni-due.de
.\"
.\" ###### Setup ############################################################
.Dd February 26, 2021
.Dt hipercontracer 1
.Os hipercontracer
.\" ###### Name #############################################################
.Sh NAME
.Nm hipercontracer
.Nd High-Performance Connectivity Tracer (HiPerConTracer)
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm hipercontracer
.Op \-P|--ping
.Op \-T|--traceroute
.Op \-L|--loglevel level
.Op \-q|--quiet
.Op \-v|--verbose
.Op \-U|--user=user|uid
.Op \-S|--source=address[,traffic_class[,...]]
.Op \-D|--destination address
.Op \--iterations number_of_iterations
.Op \--tracerouteinterval milliseconds
.Op \--tracerouteduration milliseconds
.Op \--tracerouterounds rounds
.Op \--tracerouteinitialmaxttl value
.Op \--traceroutefinalmaxttl value
.Op \--tracerouteincrementmaxttl value
.Op \--traceroutepacketsize bytes
.Op \--pinginterval milliseconds
.Op \--pingexpiration milliseconds
.Op \--pingttl value
.Op \--pingpacketsize bytes
.Op \-R|--resultsdirectory directory
.Op \--resultstransactionlength seconds
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm hipercontracer
is a Ping/Traceroute service. It performs regular Ping and Traceroute runs
among sites and can export the results into results statements for import into
a database.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments may be provided:
.Bl -tag -width indent
.It \-P|\--ping
Start the Ping service.
.It \-T|\--traceroute
Start the Traceroute service.
.It \-L|\--loglevel level
Sets the minimum logging level to the provided value: 0=trace, 1=debug, 2=info, 3=warning, 4=error, 5=fatal.
.It \-q|\--quiet
Sets the minimum logging level to 3 (warning).
.It \-v|\--verbose
Sets the minimum logging level to 0 (trace).
.It \-U|\--user user|uid
After startup, HiPerConTracer uses UID and GID of the given user (by name or GID).
The output directory's ownership as well as the ownership of the created results
files will be set accordingly.
.It \-S|\--source address[,traffic_class[,...]]
Adds the given source address. It is possible to use the ANY address (0.0.0.0 or ::), in order to just use the default route.
If no traffic class is given, Best Effort (00) is used. Otherwise, the list of given traffic classes (in hexadecimal) is used. Alternatively, a traffic class can be specified by PHB name (BE, EF, AF11, AF12, AF13, AF21, AF22, AF23, AF31, AF32, AF33, AF41, AF42, AF43, CS1, CS2, CS3, CS4, CS5, CS6, CS7). In this case, the corresponding traffic class with ECN bits set to 0 is used.
Note: use lower-case hexadecimal letters to avoid ambiguities with PHB name (e.g. be for 0xbe instead of BE PHB)!
.It \-D|\--destination address
Adds the given destination address.
.It \--iterations number_of_iterations
Limit the number of measurement iterations (measurement for all source/destination
pairs) to the given number of iterations. The default 0 lets HiPerConTracer run
continuously.
.It \--tracerouteinterval milliseconds
Sets the Traceroute interval (time for each full round of destinations).
.It \--tracerouteduration milliseconds
Sets the Traceroute duration (timeout for each destination).
.It \--tracerouterounds rounds
For each Traceroute measurement, perform the given number of rounds simultaneously.
Default is 1 round.
Each TTL test of a round will have the same ICMP checksum value ("Oslo Traceroute"),
in order to deal with load balancing in the Internet.
Different rounds will have different checksums. That is, different rounds may
experience different paths in the network.
.It \--tracerouteinitialmaxttl value
Start with the given maximum TTL.
.It \--traceroutefinalmaxttl value
Finish with the given maximum TTL
(when destination is not reached with current TTL setting).
.It \--tracerouteincrementmaxttl value
Increase the maximum TTL by the given value
(when destination is not reached with current TTL setting).
.It \--traceroutepacketsize bytes
Sets the Traceroute packet size, that is IP header (20 for IPv4/40 for IPv6) + ICMP header (8) + HiPerConTracer header (16) + payload, in bytes.
The actually sent packet size always covers at least the headers for IPv4/IPv6, ICMP and HiPerConTracer. Maximum packet size is 65535.
.It \--pinginterval milliseconds
Sets the Ping interval (time for each full round of destinations).
.It \--pingexpiration milliseconds
Sets the Ping duration (timeout for each destination).
.It \--pingttl value
Sets the Ping TTL value.
.It \--pingpacketsize bytes
Sets the Ping packet size, that is IP header (20 for IPv4/40 for IPv6) + ICMP header (8) + HiPerConTracer header (16) + payload, in bytes.
The actually sent packet size always covers at least the headers for IPv4/IPv6, ICMP and HiPerConTracer. Maximum packet size is 65535.
.It \-R|\--resultsdirectory directory
Sets the results files directory. The results will be stored there. If not specified, to results will be stored.
.It \--resultstransactionlength seconds
After a given number of seconds, begin a new results file.
.El
.\" ###### Output format ####################################################
.Sh OUTPUT FORMAT
The output file is a BZip2-compressed text file. The format is as follows, depending on the measurement type:
.Bl -tag -width indent
.It Ping
Each Ping entry consists of a #P line.
.Bl -tag -width indent
.It #P sourceIP destinationIP timestamp checksum status rtt traffic_class
.Bl -tag -width indent
.It * sourceIP: Source IP address.
.It * destinationIP: Destination IP address.
.It * timestamp: Timestamp (microseconds since the UTC epoch, hexadecimal).
.It * checksum: The checksum of the ICMP Echo Request packets (hexadecimal).
.It * status: Status code (decimal):
.Bl -tag -width indent
.It - 1 = ICMP response: Time Exceeded
.It - 100 = ICMP response: Unreachable scope
.It - 101 = ICMP response: Unreachable network
.It - 102 = ICMP response: Unreachable host
.It - 103 = ICMP response: Unreachable protocol
.It - 104 = ICMP response: Unreachable port
.It - 105 = ICMP response: Unreachable, prohibited (firewall)
.It - 110 = ICMP response: Unreachable, unknown reason
.It - 200 = Timeout (no response from a router)
.It - 255 = Success (destination has responded)
.El
Status values from 100 to 199 denote unreachability, as reported by ICMP error from a router. The rtt field contains the response time of the corresponding router.
Status values from 200 to 254 have the destination IP in their destinationIP field. However, there was no response from a router, so the rtt field will be the configured timeout value!
.It * rtt: The measured RTT (microseconds, decimal).
.It * traffic_class: The outgoing IP Traffic Class/Type of Service value of the ICMP Echo Request packets (hexadecimal). This entry has been added with HiPerConTracer 1.4.0!
.It * packet_size: The sent packet size (decimal, in bytes) including IPv4/IPv6 header, ICMP header and HiPerConTracer header.
This entry has been added with HiPerConTracer 1.6.0!
.El
.El
.It Traceroute
Each Traceroute entry begins with a #T line, plus one TAB-started line per hop.
.Bl -tag -width indent
.It #T sourceIP destinationIP timestamp round totalHops statusFlags pathHash traffic_class
.Bl -tag -width indent
.It * sourceIP: Source IP address.
.It * destinationIP: Destination IP address.
.It * timestamp: Timestamp (microseconds since the UTC epoch, hexadecimal).
.It * round: Round number.
.It * checksum: The checksum of the ICMP Echo Request packets (hexadecimal).
.It * totalHops: Total hops.
.It * statusFlags: Status flags (hexadecimal):
See the status code for Ping above for the lower 8 bits. Additionally:
.Bl -tag -width indent
.It - 0x100 = Route with * (at least one router did not respond)
.It - 0x200 = Destination has responded
.El
.It * pathHash: Hash of the path (hexadecimal).
.It * traffic_class: The outgoing IP Traffic Class/Type of Service value of the ICMP Echo Request packets (hexadecimal).
This entry has been added with HiPerConTracer 1.4.0!
.It * packet_size: The sent packet size (decimal, in bytes) including IPv4/IPv6 header, ICMP header and HiPerConTracer header.
This entry has been added with HiPerConTracer 1.6.0!
.El
.It (TAB) hopNumber status rtt hopIP
.Bl -tag -width indent
.It * hopNumber: Number of the hop.
.It * status: Status code (hexadecimal here(!); the values are the same as for Ping, see above).
.It * rtt: The measured RTT (microseconds, decimal).
.It * hopIP: Hop IP address.
.El
.El
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It hipercontracer \-S 10.1.1.51 \-D 10.1.1.6 \-D 10.1.1.7 \-D 10.1.1.8 \-T \--tracerouteinterval 10000 \--tracerouteduration 1000 \-v
.It hipercontracer \--source 10.1.1.51 \--destination 10.1.1.6 \--destination 10.1.1.7 \--destination 10.1.1.8 \--traceroute \--tracerouteinterval 10000 \--tracerouteduration 1000
.It hipercontracer \--source 172.16.0.127 \--destination 8.8.8.8 \--destination 193.99.144.80 \--destination 132.252.181.87 \--destination 10.254.254.254 \--destination 91.189.93.5 \--destination 128.112.139.90 \--destination 4.31.198.44 \--destination 136.186.1.10 \--destination 101.4.112.170 \--destination 77.36.144.2 \--source 2a02:270:2014:40:92e2:baff:fe48:bde1 \--destination 2400:cb00:2048:1::6814:155 \--destination 2a02:2e0:3fe:1001:7777:772e:2:85 \--destination 2a00:1450:400f:805::2004 \--traceroute \--ping \--tracerouteduration 1000 \--tracerouteinitialmaxttl 4 \--traceroutefinalmaxttl 32 \--tracerouteincrementmaxttl 4 \--pinginterval 1000 \--pingexpiration 7500 \--pingttl 56 \--resultsdirectory results
.It hipercontracer \--source=0.0.0.0,00,AF11 \--source=::,BE,EF,AF11 \--destination=8.8.8.8 \--destination=2606:4700:10::6814:155 \--ping \--traceroute \--tracerouteduration=1000 \--tracerouteinitialmaxttl=4 \--traceroutefinalmaxttl=32 \--tracerouteincrementmaxttl=4 \--pinginterval=1000 \--pingexpiration=7500 \--pingttl=56 \--resultsdirectory=/storage/hpct-results \--resultstransactionlength=20 \--quiet
.It hipercontracer \--user=hipercontracer \--source=10.1.1.51 \--destination=10.1.1.6 \--destination=10.1.1.7 \--destination=10.1.1.8 \--traceroute \--tracerouteinterval=10000 \--tracerouteduration=1000
.It hipercontracer \--user=hipercontracer \--source=0.0.0.0 \--destination=8.8.8.8 \--ping \--verbose
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.uni-due.de/~be0001/hipercontracer
.br
mailto://dreibh@iem.uni-due.de
.br
