.\" ========================================================================
.\"    _   _ _ ____            ____          _____
.\"   | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
.\"   | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
.\"   |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
.\"   |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
.\"
.\"      ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
.\"                https://www.nntb.no/~dreibh/hipercontracer/
.\" ========================================================================
.\"
.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd April 11, 2025
.Dt hpct-importer 1
.Os hpct-importer
.\" ###### Name #############################################################
.Sh NAME
.Nm hpct-importer
.Nd HiPerConTracer Trace Data Importer
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm hpct-importer
.Op Fl C Ar importer_configuration | Fl Fl importer-config Ar importer_configuration
.Op Fl D Ar database_configuration | Fl Fl database-config Ar database_configuration
.Op Fl L Ar level | Fl Fl loglevel Ar level
.Op Fl Z Ar on|off | Fl Fl logcolor Ar on|off
.Op Fl O Ar file | Fl Fl logfile Ar file
.Op Fl q | Fl Fl quiet
.Op Fl v | Fl Fl verbose
.Op Fl X Ar mode | Fl Fl import-mode Ar mode
.Op Fl Y Ar depth | Fl Fl import-max-depth Ar depth
.Op Fl I Ar path | Fl Fl import-file-path Ar path
.Op Fl B Ar path | Fl Fl bad-file-path Ar path
.Op Fl G Ar path | Fl Fl good-file-path Ar path
.Op Fl F Ar filter_regexp | Fl Fl import-file-path-filter Ar filter_regexp
.Op Fl Q | Fl Fl quit-when-idle
.Op Fl Fl ping-workers Ar number
.Op Fl Fl ping-files Ar number
.Op Fl Fl traceroute-workers Ar number
.Op Fl Fl traceroute-files Ar number
.\" .Op Fl Fl jitter-workers Ar number
.\" .Op Fl Fl jitter-files Ar number
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm hpct-importer
imports HiPerConTracer results into an SQL or NoSQL database. Currently, the
following database backends are supported:
MySQL/MariaDB (SQL),
PostgreSQL (SQL),
MongoDB (NoSQL).
.br
Results files imported successfully can be moved into a "good" directory,
deleted or kept as-in (for debugging only!).
Results files which failed to import a re moved into a "bad" directory.
.br
The input of multiple input files can be combined into a single database
transaction, to improve performance on short files. In case of an import
error, each file is imported sequentially to identify faulty ones.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following argument may be provided:
.Bl -tag -width indent
.It Fl L Ar level | Fl Fl loglevel Ar level
Sets the minimum logging level to the provided value: 0=trace, 1=debug, 2=info, 3=warning, 4=error, 5=fatal.
.It Fl Z Ar on|off | Fl Fl logcolor Ar on|off
Enables (on) or disables (off) the usage of ANSI color escape sequences to colorise the log output according to its level.
.It Fl O Ar file | Fl Fl logfile Ar file
Sets a file name for appending the log output to. If a file is set, no log output is made to the console.
Otherwise, all log output will be written to the console.
.It Fl q | Fl Fl quiet
Sets the minimum logging level to 3 (warning).
.It Fl v | Fl Fl verbose
Sets the minimum logging level to 0 (trace).
.It Fl C Ar importer_configuration | Fl Fl importer-config Ar importer_configuration
Sets the name of the importer configuration file. This option must be provided!
.br
See /usr/share/hipercontracer/hipercontracer-importer.conf for an example.
.It Fl D Ar database_configuration | Fl Fl database-config Ar database_configuration
Sets the name of the database configuration file. This option must be provided!
.br
See /usr/share/hipercontracer/hipercontracer-database.conf for an example.
.It Fl X Ar mode | Fl Fl import-mode Ar mode
Specifies the import mode,
overriding the mode read from the database configuration file:
DeleteImportedFiles (delete successfully imported files)
MoveImportedFiles (move successfully imported files into "good" directory),
KeepImportedFiles (keep successfully imported files where they are).
Do not use KeepImportedFiles execpt for testing. Otherwise, the next re-run of
hpct-importer tries to import them again! They may create duplicates when the
underlying database system (e.g. NoSQL without unique indices) does not ensure
uniqueness!
.It Fl Y Ar depth | Fl Fl import-max-depth Ar depth
Specifies the import directory traversal depth,
overriding the mode read from the database configuration file.
.It Fl I Ar path | Fl Fl import-file-path Ar path
Specifies the import file path,
overriding the mode read from the database configuration file.
This path is used to look for files to import.
.It Fl B Ar path | Fl Fl bad-file-path Ar path
Specifies the "good" file path,
overriding the mode read from the database configuration file.
This path is used to move successfully imported files to, when
the import mode is set to KeepImportedFiles.
.It Fl G Ar path | Fl Fl good-file-path Ar path
Specifies the "bad" file path,
overriding the mode read from the database configuration file.
This path is used to move files to which failed to import.
.It Fl F Ar filter_regexp | Fl Fl import-file-path-filter Ar filter_regexp
Specifies the import path filter,
overriding the mode read from the database configuration file.
This filter can be used to only import a subset of the import files for
testing. The filter expression is an std::regex regular expression.
.It Fl Q | Fl Fl quit-when-idle
Quit importer when all workers are idle. This will perform only one import
round.
.It Fl Fl ping-workers Ar number
Sets the number of Ping import workers. Default: 1.
An import file is distributed to a worker by hashing the source address
given in the file name.
.It Fl Fl ping-files Ar number
Sets the number of Ping import files per database transaction. Default: 1.
.It Fl Fl traceroute-workers Ar number
Sets the number of Traceroute import workers. Default: 1.
An import file is distributed to a worker by hashing the source address
given in the file name.
.It Fl Fl traceroute-files Ar number
Sets the number of Traceroute import files per database transaction. Default: 1.
.\" .It Fl Fl jitter-workers Ar number
.\" Sets the number of Jitter import workers. Default: 1.
.\" An import file is distributed to a worker by hashing the source address
.\" given in the file name.
.\" .It Fl Fl jitter-files Ar number
.\" Sets the number of Jitter import files per database transaction. Default: 1.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It hpct-importer -C hipercontracer-importer.conf -D hipercontracer-database.conf
.It hpct-importer --importer-config hipercontracer-importer.conf --database-config hipercontracer-database.conf --verbose
.It hpct-importer -C hipercontracer-importer.conf -D hipercontracer-database.conf -F "1234/.*"
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/hipercontracer
.br
mailto://dreibh@simula.no
.br
