.\" ========================================================================
.\"    _   _ _ ____            ____          _____
.\"   | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
.\"   | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
.\"   |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
.\"   |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
.\"
.\"      ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
.\"                https://www.nntb.no/~dreibh/hipercontracer/
.\" ========================================================================
.\"
.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd April 11, 2025
.Dt hpct-node-setup 1
.Os hpct-node-setup
.\" ###### Name #############################################################
.Sh NAME
.Nm hpct-node-setup
.Nd HiPerConTracer Node
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm hpct-node-setup USER@COLLECTOR NODE_ID
.Op Fl h | Fl Fl help
.Op Fl v | Fl Fl verbose
.Op Fl q | Fl Fl quiet
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm hpct-node-setup
is the HiPerConTracer node setup script. It is run on a node, in order to:
.Bl -tag -width indent
.It 1. Create an SSH key pair (for public/private key-based authentication to collector);
.It 2. Upload the public key to the collector;
.It 3. Configure SSH public/private key-based authentication on the collector (for SSH node->collector; Note: this configures password-less login to the node user node<NODE_ID> on the collector!);
.It 4. Update known_hosts on the collector with node's server key (for SSH collector->node via Reverse Tunnel; Note: this direction is *not* configured, for security!).
.It 5. Update /etc/hipercontracer/hpct-sync.conf with the given ID and collector.
.El
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments must be provided:
.Bl -tag -width indent
.It USER@COLLECTOR
Sets the SSH location of the collector, i.e. USER@HOST.EXAMPLE.
.It NODE_ID
Sets the node ID, a number from 1 to 9999.
.It Fl h | Fl Fl help
Prints command help.
.It Fl q |\--quiet
Turns off status output.
.It Fl v |\--verbose
Turns on status output.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It sudo hpct-node-setup nornetpp@hpct-collector.example 1
.It sudo hpct-node-setup nornetpp@hpct-collector.example 1000
.It sudo hpct-node-setup nornetpp@hpct-collector.example 2000 --verbose
.It sudo hpct-node-setup nornetpp@hpct-collector.example 2001 -v
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.simula.no/people/dreibh
.br
mailto://dreibh@simula.no
.br
