.\" ========================================================================
.\"    _   _ _ ____            ____          _____
.\"   | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
.\"   | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
.\"   |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
.\"   |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
.\"
.\"      ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
.\"                https://www.nntb.no/~dreibh/hipercontracer/
.\" ========================================================================
.\"
.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd October 31, 2024
.Dt hpct-trigger 1
.Os hpct-trigger
.\" ###### Name #############################################################
.Sh NAME
.Nm hpct-trigger
.Nd High-Performance Connectivity Tracer (HiPerConTracer) Trigger Tool
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm hpct-trigger
.Op Fl Fl triggerpingage Ar seconds
.Op Fl Fl triggerpingpacketsize Ar payload_length
.Op Fl Fl triggerpingsbeforequeuing Ar count
.Op Fl P | Fl Fl ping
.Op Fl T | Fl Fl traceroute
.\" .Op Fl J | Fl Fl jitter
.Op Fl L Ar level | Fl Fl loglevel Ar level
.Op Fl Z Ar on|off | Fl Fl logcolor Ar on|off
.Op Fl O Ar file | Fl Fl logfile Ar file
.Op Fl q | Fl Fl quiet
.Op Fl v | Fl Fl verbose
.Op Fl U Ar user|uid |  Fl Fl user Ar user|uid
.Op Fl # Ar identifier |  Fl Fl measurement-id Ar identifier
.Op Fl S Ar address|hostname[,traffic_class[,...]] | Fl Fl source Ar address|hostname[,traffic_class[,...]]
.Op Fl D Ar address|hostname | Fl Fl destination Ar address|hostname
.Op Fl Fl sources-from-file Ar file
.Op Fl Fl destinations-from-file Ar file
.Op Fl M Ar ICMP|UDP | Fl Fl iomodule Ar ICMP|UDP
.Op Fl I Ar number_of_iterations | Fl Fl iterations Ar number_of_iterations
.Op Fl Fl tracerouteinterval Ar milliseconds
.Op Fl Fl tracerouteintervaldeviation Ar fraction
.Op Fl Fl tracerouteduration Ar milliseconds
.Op Fl Fl tracerouterounds Ar rounds
.Op Fl Fl tracerouteinitialmaxttl Ar value
.Op Fl Fl traceroutefinalmaxttl Ar value
.Op Fl Fl tracerouteincrementmaxttl Ar value
.Op Fl Fl traceroutepacketsize Ar bytes
.Op Fl Fl tracerouteudpsourceport Ar port
.Op Fl Fl tracerouteudpdestinationport Ar port
.Op Fl Fl pinginterval Ar milliseconds
.Op Fl Fl pingintervaldeviation Ar fraction
.Op Fl Fl pingexpiration Ar milliseconds
.Op Fl Fl pingburst Ar packets
.Op Fl Fl pingttl Ar value
.Op Fl Fl pingpacketsize Ar bytes
.Op Fl Fl pingudpsourceport Ar port
.Op Fl Fl pingudpdestinationport Ar port
.\" .Op Fl Fl jitterinterval Ar milliseconds
.\" .Op Fl Fl jitterintervaldeviation Ar fraction
.\" .Op Fl Fl jitterexpiration Ar milliseconds
.\" .Op Fl Fl jitterburst Ar packets
.\" .Op Fl Fl jitterttl Ar value
.\" .Op Fl Fl jitterpacketsize Ar bytes
.\" .Op Fl Fl jitterrecordraw
.\" .Op Fl Fl jitterudpsourceport Ar port
.\" .Op Fl Fl jitterudpdestinationport Ar port
.Op Fl R Ar directory | Fl Fl resultsdirectory Ar directory
.Op Fl x Ar seconds | Fl Fl resultstransactionlength Ar seconds
.Op Fl C Ar none|XZ|BZip2|GZip | Fl Fl resultscompression Ar none|XZ|BZip2|GZip
.Op Fl F Ar version | Fl Fl resultsformat Ar version
.Op Fl z Ar depth | Fl Fl resultstimestampdepth Ar depth
.Op Fl Fl check
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm hpct-trigger
is a tool to trigger HiPerConTracer measurement, based on observed incoming ICMP Ping packets. Once the given number of such packets with a given size has been observed from a source, a Ping or Traceroute is triggered to the corresponding remote address.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments may be provided:
.Bl -tag -width indent
.It Fl Fl triggerpingage Ar seconds
Sets the maximum number of seconds between two trigger "Pings" (default: 300).
.It Fl Fl triggerpingpacketsize Ar payload_length
Sets the "Ping" total length (IP header + ICMP header + HiPerCOnTracer header) to trigger a HiPerConTracer measurement (default: 67).
.It Fl Fl triggerpingsbeforequeuing Ar count
Sets the number of observed "Ping" packets before triggering HiPerConTracer
(default: 3).
.El
See the manual page of HiPerConTracer for the other arguments and the output
format.
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It hpct-trigger \-\-source 10.1.1.51 \-\-traceroute \-\-verbose \-\-triggerpingsbeforequeuing 2 \-\-triggerpingpacketsize 88
.It hpct-trigger \-\-source 10.1.1.51 \-\-triggerpingage 1800 \-\-ping \-\-verbose
.It hpct-trigger \-\-source=10.1.1.51 \-\-traceroute \-\-resultsdirectory=/tmp/results \-\-resultstransactionlength=60 \-\-resultstimestampdepth 3
.It hpct-trigger \-\-source=172.16.1.2,BE,EF \-\-source=172.17.1.2,BE,AF11,AF21 \-\-triggerpingage=1800 \-\-ping \-\-verbose
.It hpct-trigger \-\-source 10.1.1.51 \-\-triggerpingage 1800 \-\-ping \-\-traceroute \-\-iomodule ICMP \-\-iomodule UDP
.It hipercontracer -S 0.0.0.0 -S :: -D <TARGET> --ping --pingpacketsize 67 --iterations 3 --verbose
.It hipercontracer -S 0.0.0.0 -S :: -D <TARGET> -P --pingpacketsize 88 -I 3 -v
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/hipercontracer
.br
mailto://dreibh@simula.no
.br
