.\" ========================================================================
.\"    _   _ _ ____            ____          _____
.\"   | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
.\"   | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
.\"   |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
.\"   |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
.\"
.\"      ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
.\"                https://www.nntb.no/~dreibh/hipercontracer/
.\" ========================================================================
.\"
.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd April 11, 2025
.Dt hpct-query 1
.Os hpct-query
.\" ###### Name #############################################################
.Sh NAME
.Nm hpct-query
.Nd HiPerConTracer Query Tool
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm hpct-query
database_configuration
ping|traceroute
.Op Fl L Ar level | Fl Fl loglevel Ar level
.Op Fl Z Ar on|off | Fl Fl logcolor Ar on|off
.Op Fl O Ar file | Fl Fl logfile Ar file
.Op Fl q | Fl Fl quiet
.Op Fl v | Fl Fl verbose
.Op Fl o Ar filename | Fl Fl output Ar filename
.Op Fl T Ar table_name | Fl Fl table Ar table_name
.Op Fl V Ar version | Fl Fl table-version Ar version
.Op Fl M Ar mapping_file | Fl Fl address-to-measurementid Ar mapping_file
.Op Fl Fl deduplication Ar on|off
.Op Fl Fl from-time Ar timestamp
.Op Fl Fl to-time Ar timestamp
.Op Fl Fl from-measurement-id Ar measurement_identifier
.Op Fl Fl to-measurement-id Ar measurement_identifier
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm hpct-query
provides a simple query command to query a HiPerConTracer database for
Ping or Traceroute results within a given time range. The output format is
that same as the uncompressed HiPerConTracer results formant. See the
HiPerConTracer manpage for the format description.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following argument may be provided:
.Bl -tag -width indent
.It Fl L Ar level | Fl Fl loglevel Ar level
Sets the minimum logging level to the provided value: 0=trace, 1=debug, 2=info, 3=warning, 4=error, 5=fatal.
.It Fl Z Ar on|off | Fl Fl logcolor Ar on|off
Enables (on) or disables (off) the usage of ANSI color escape sequences to colorise the log output according to its level.
.It Fl O Ar file | Fl Fl logfile Ar file
Sets a file name for appending the log output to. If a file is set, no log output is made to the console.
Otherwise, all log output will be written to the console.
.It Fl q | Fl Fl quiet
Sets the minimum logging level to 3 (warning).
.It Fl v | Fl Fl verbose
Sets the minimum logging level to 0 (trace).
.It Fl o Ar filename | Fl Fl output Ar filename
Sets the specified filename as output file. Extensions \.gz, \.bz2, and \.xz are recognised to enable compression.
.It Fl T Ar table_name | Fl Fl table Ar table_name
Sets a custom table name to query from.
.It Fl V Ar version | Fl Fl tabl-version Ar version
Sets the table version (default is: 2). This option is to be used to read a table from on older HiPerConTracer schema version.
.It Fl M Ar mapping_file | Fl Fl address-to-measurementid Ar mapping_file
Sets a mapping file, containing space-separated IP address to measurement ID mappings with one mapping per line. Where measurement ID is zero, the measurement ID is looked up from the mappings. This option can be used to later map measurements to a useful measurement ID for export.
Example mapping file contents:
.br
1.2.3.4 1000
.br
3ffe::1:2:3 1000
.br
5.6.7.8 2222
.br
2001::1:2:3 2222
.br
...
.It Fl Fl deduplication Ar on|off
Perform deduplication of the output. This option is for debugging, or to handle badly misconfigured database schemata where there primary index is non-unique. In almost all cases, this option is unnecessary and should be turned off. Default: off.
.It Fl Fl from-time Ar timestamp
Set the beginning of the time range as string in format "%Y-%m-%d %H:%M:%S.%F".
If not provided, all results will be queried.
.It Fl Fl to-time Ar timestamp
Set the end of the time range as string in format "%Y-%m-%d %H:%M:%S.%F".
If not provided, all results after a given from-time will be queried.
Note: data at to-time timestamp is not included in the export, only time stamps less than to-time! That is, the time interval for export is [from-timestamp, to-timestamp). This ensures the possibility to for example export daily batches without having the same value included in two files!
.It Fl Fl from-measurement-id Ar measurement_identifier
Set the beginning of the measurement identifier range.
If not provided, all results will be queried.
.It Fl Fl to-measurement-id Ar measurement_identifier
Set the end of the measurement identifier range.
If not provided, all results will be queried.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It hpct-query hipercontracer-database.conf ping
.It hpct-query hipercontracer-database.conf traceroute
.It hpct-query hipercontracer-database.conf ping --from-time "2022-09-29 13:00:00"
.It hpct-query hipercontracer-database.conf traceroute --from-time "2022-09-29 00:00:00" --to-time "2022-09-29 12:00:00"
.It hpct-query hipercontracer-database.conf traceroute --from-measurement-id 1000 --to-measurement-id 2000
.It hpct-query hipercontracer-database.conf traceroute --from-measurement-id 1000 --to-measurement-id 2000 --output results.xz
.It hpct-query hipercontracer-database.conf ping --table test_ping_table
.It hpct-query hipercontracer-database.conf traceroute -T Traceroute_v1 -V 1 --from-time 2015-10-16 --to-time 2015-10-17 -o "Traceroute-2015-10-16.hpct.xz" -M addressmappings.txt
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/hipercontracer
.br
mailto://dreibh@simula.no
.br
