.\" ========================================================================
.\"    _   _ _ ____            ____          _____
.\"   | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
.\"   | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
.\"   |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
.\"   |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
.\"
.\"      ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
.\"                https://www.nntb.no/~dreibh/hipercontracer/
.\" ========================================================================
.\"
.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd April 11, 2025
.Dt hpct-ssh 1
.Os hpct-ssh
.\" ###### Name #############################################################
.Sh NAME
.Nm hpct-ssh
.Nd HiPerConTracer SSH via Reverse Tunnel
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm hpct-ssh USER@NODE_ID
.Op Fl h | Fl Fl help
.Op Fl v | Fl Fl verbose
.Op Fl q | Fl Fl quiet
.Op Fl c | Fl Fl copy-id
.Op Fl Fl
SSH_ARGUMENTS ...
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm hpct-ssh
is the HiPerConTracer Reverse Tunnel SSH script. It is to be run
on the Collector and provides SSH login via reverse tunnel to a given node.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments must be provided:
.Bl -tag -width indent
.It Fl h | Fl Fl help
Prints command help.
.It Fl q |\--quiet
Turns off status output.
.It Fl v |\--verbose
Turns on status output.
.It Fl c | Fl Fl copy-id
Calls ssh-copy-id first, in order to configure public/private key-based
authentication to the remote node. If successful, SSH is tried. This should
provide a password-less login.
.It Fl Fl
All arguments after -- are provided to the SSH call.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It hpct-ssh user@1000
.It hpct-ssh user@1000 --verbose
.It hpct-ssh user@1000 --copy-id --verbose
.It hpct-ssh user@1000 --quiet -- 'hostname ; pactl list sources'
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.simula.no/people/dreibh
.br
mailto://dreibh@simula.no
.br
