.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2021 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@iem.uni-due.de
.\"
.\" ###### Setup ############################################################
.Dd June 6, 2019
.Dt hpcttrigger 1
.Os hpcttrigger
.\" ###### Name #############################################################
.Sh NAME
.Nm hpcttrigger
.Nd High-Performance Connectivity Tracer (HiPerConTracer) Trigger Tool
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm hpcttrigger
.Op \-P|--ping
.Op \-T|--traceroute
.Op \-L|--loglevel level
.Op \-q|--quiet
.Op \-v|--verbose
.Op \-U|--user user|uid
.Op \-S|--source address[,traffic_class[,...]]
.Op \-D|--destination address
.Op \--tracerouteinterval milliseconds
.Op \--tracerouteduration milliseconds
.Op \--tracerouterounds rounds
.Op \--tracerouteinitialmaxttl value
.Op \--traceroutefinalmaxttl value
.Op \--tracerouteincrementmaxttl value
.Op \--pinginterval milliseconds
.Op \--pingexpiration milliseconds
.Op \--pingttl value
.Op \-R|--resultsdirectory directory
.Op \--resultstransactionlength seconds
.Op \--pingtriggerage seconds
.Op \--pingtriggerlength payload_length
.Op \--pingsbeforequeuing count
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm hpcttrigger
is a tool to trigger HiPerConTracer runs, based on observed incoming "Ping"
packets. Once the given number of such packets with a given size has been
observed from a source, a Ping or Traceroute is triggered to the corresponding
address.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments may be provided:
.Bl -tag -width indent
.It \--pingtriggerage seconds
Sets the maximum number of seconds between two trigger "Pings" (default: 300).
.It \--pingtriggerlength payload_length
Sets the "Ping" payload length to trigger HiPerConTracer (default: 53).
.It \--pingsbeforequeuing count
Sets the number of observed "Ping" packets before triggering HiPerConTracer
(default: 3).
.El
See the manual page of HiPerConTracer for the other arguments and the output
format.
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It hpcttrigger \--source 10.1.1.51 \--traceroute \--verbose \--pingsbeforequeuing 2 \--pingtriggerlength 88
.It hpcttrigger \--source 10.1.1.51 \--pingtriggerage 1800 \--ping \--verbose
.It hpcttrigger \--source=10.1.1.51 \--traceroute \--resultsdirectory=/tmp/results \--resultstransactionlength=60
.It hpcttrigger \--source=172.16.1.2,BE,EF \--source=172.17.1.2,BE,AF11,AF21 \--pingtriggerage=1800 \--ping \--verbose
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.uni-due.de/~be0001/hipercontracer
.br
mailto://dreibh@iem.uni-due.de
.br
