.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2024 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd December 1, 2023
.Dt hpct-trigger 1
.Os hpct-trigger
.\" ###### Name #############################################################
.Sh NAME
.Nm hpct-trigger
.Nd High-Performance Connectivity Tracer (HiPerConTracer) Trigger Tool
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm hpct-trigger
.Op \-P|\-\-ping
.Op \-T|\-\-traceroute
.Op \-L|\-\-loglevel level
.Op \-Z|\-\-logcolor on|off
.Op \-O|\-\-logfile file
.Op \-q|\-\-quiet
.Op \-v|\-\-verbose
.Op \-U|\-\-user user|uid
.Op \-#|\-\-measurement-id identifier
.Op \-S|\-\-source address|hostname[,traffic_class[,...]]
.Op \-D|\-\-destination address|hostname
.Op \-\-sources-from-file file
.Op \-\-destinations-from-file file
.Op \-M|\-\-iomodule ICMP|UDP
.Op \-\-tracerouteinterval milliseconds
.Op \-\-tracerouteduration milliseconds
.Op \-\-tracerouterounds rounds
.Op \-\-tracerouteinitialmaxttl value
.Op \-\-traceroutefinalmaxttl value
.Op \-\-tracerouteincrementmaxttl value
.Op \-\-traceroutepacketsize bytes
.Op \-\-tracerouteudpsourceport port
.Op \-\-tracerouteudpdestinationport port
.Op \-\-pinginterval milliseconds
.Op \-\-pingexpiration milliseconds
.Op \-\-pingburst packets
.Op \-\-pingttl value
.Op \-\-pingpacketsize bytes
.Op \-\-pingudpsourceport port
.Op \-\-pingudpdestinationport port
.Op \-\-jitterinterval milliseconds
.Op \-\-jitterintervaldeviation fraction
.Op \-\-jitterexpiration milliseconds
.Op \-\-jitterburst packets
.Op \-\-jitterttl value
.Op \-\-jitterpacketsize bytes
.Op \-\-jitterrecordraw
.Op \-\-jitterudpsourceport port
.Op \-\-jitterudpdestinationport port
.Op \-R|\-\-resultsdirectory directory
.Op \-l|\-\-resultstransactionlength seconds
.Op \-C|\-\-resultscompression none|XZ|BZip2|GZip
.Op \-F|\-\-resultsformat version
.Op \-\-check
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm hpct-trigger
is a tool to trigger HiPerConTracer runs, based on observed incoming "Ping"
packets. Once the given number of such packets with a given size has been
observed from a source, a Ping or Traceroute is triggered to the corresponding
address.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments may be provided:
.Bl -tag -width indent
.It \-\-pingtriggerage seconds
Sets the maximum number of seconds between two trigger "Pings" (default: 300).
.It \-\-pingtriggerlength payload_length
Sets the "Ping" payload length to trigger HiPerConTracer (default: 53).
.It \-\-pingsbeforequeuing count
Sets the number of observed "Ping" packets before triggering HiPerConTracer
(default: 3).
.El
See the manual page of HiPerConTracer for the other arguments and the output
format.
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It hpct-trigger \-\-source 10.1.1.51 \-\-traceroute \-\-verbose \-\-pingsbeforequeuing 2 \-\-pingtriggerlength 88
.It hpct-trigger \-\-source 10.1.1.51 \-\-pingtriggerage 1800 \-\-ping \-\-verbose
.It hpct-trigger \-\-source=10.1.1.51 \-\-traceroute \-\-resultsdirectory=/tmp/results \-\-resultstransactionlength=60
.It hpct-trigger \-\-source=172.16.1.2,BE,EF \-\-source=172.17.1.2,BE,AF11,AF21 \-\-pingtriggerage=1800 \-\-ping \-\-verbose
.It hpct-trigger \-\-source 10.1.1.51 \-\-pingtriggerage 1800 \-\-ping \-\-traceroute \-\-iomodule ICMP \-\-iomodule UDP
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/hipercontracer
.br
mailto://thomas.dreibholz@gmail.com
.br
