#!/usr/bin/env bash
# ==========================================================================
#     _   _ _ ____            ____          _____
#    | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
#    | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
#    |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
#    |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
#
#       ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
#                 https://www.nntb.no/~dreibh/hipercontracer/
# ==========================================================================
#
# High-Performance Connectivity Tracer (HiPerConTracer)
# Copyright (C) 2015-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


echo "Active devices and drivers:"
for name in /sys/class/net/* ; do
   device="$(basename "${name}")"
   driverModule="$(readlink "${name}"/device/driver/module)"
   if [ "${driverModule}" != "" ]; then
      driverModule="$(basename "${driverModule}")"
   fi
   operstate="$(cat "${name}"/operstate)"
   if [ "${operstate}" != "down" ] ; then
      mac="$(cat "${name}"/address)"
      businfo="$(ethtool -i "${device}" 2>/dev/null | grep "^bus-info:" | sed -e "s/[^:]*: //g")"
      printf "%-16s %-18s %-18s %-20s %-16s\n" "${device}" "${mac}" "${driverModule}" "${operstate}" "${businfo}"
   fi
done
