#!/usr/bin/env bash

set -euo pipefail

# NOTE:
# This script runs a simple importer test, by importing the example data files
# under examples/. The result can be checked by run-query-test, which generates
# HiPerConTracer data statements as in the input files.

if [ $# -ne 2 ] ; then
   echo >&2 "Usage: $0 database_configuration_file importer_configuration_file"
   exit 1
fi
DATABASE_CONFIGURATION_FILE="$1"
if [ ! -e "${DATABASE_CONFIGURATION_FILE}" ] ; then
   echo >&2 "ERROR: Use database configuration ${DATABASE_CONFIGURATION_FILE} does not exist!"
fi
IMPORTER_CONFIGURATION_FILE="$2"
if [ ! -e "${IMPORTER_CONFIGURATION_FILE}" ] ; then
   echo >&2 "ERROR: Use importer configuration ${IMPORTER_CONFIGURATION_FILE} does not exist!"
fi

mkdir -p data/ good/ bad/
rm -rf good/*
rm -rf bad/*
cp results-examples/*.hpct* data/

make hpct-importer && \
rm -f core &&  \
./hpct-importer \
   -C "${IMPORTER_CONFIGURATION_FILE}" \
   -D "${DATABASE_CONFIGURATION_FILE}" \
   --traceroute-workers 1 \
   --ping-workers 1 \
   --loglevel 0 \
   --quit-when-idle

