#!/bin/sh


make -j8 hipercontracer && \
rm -f core && \
sudo ./debug.memcheck ./hipercontracer \
   -# 12345678 \
   -R results \
   --resultstransactionlength=900 \
   --iomodule icmp \
   --source=0.0.0.0 \
   --source=:: \
   --destination=8.8.8.8 -destination=193.99.144.80 -destination=104.16.45.99 \
   --destination=2001:4860:4860::8888 --destination=2a02:2e0:3fe:1001:7777:772e:2:85 --destination=2606:4700::6810:2c63 \
   --traceroute \
   --ping \
   --jitter \
   --tracerouterounds 3 \
   --tracerouteduration=1000 \
   --tracerouteinitialmaxttl=4 \
   --traceroutefinalmaxttl=32 \
   --tracerouteincrementmaxttl=4 \
   --pinginterval=1000 \
   --pingexpiration=7500 \
   --pingttl=56 \
   --pingburst=4 \
   --jitterinterval=300000 \
   $@
