#!/bin/sh

# ./debug.helgrind
# ./debug.memcheck

make -j8 && \
sudo ./hpcttrigger \
   -source=158.36.79.183 \
   -traceroute \
   -tracerouteduration=1000 \
   -tracerouteinitialmaxttl=4 \
   -traceroutefinalmaxttl=32 \
   -tracerouteincrementmaxttl=4 \
   -pinginterval=1000 \
   -pingexpiration=7500 \
   -pingttl=56 \
   -resultsdirectory=/tmp/xy \
   -resultstransactionlength=20 \
   -verbose \
   $@
