#!/bin/sh

# sudo ./debug.memcheck
# -destination=193.99.144.80 -destination=132.252.181.87 -destination=172.31.255.254 -destination=210.37.45.148

make -j8 && \
sudo ./hipercontracer \
   -source=158.36.79.183,00,2e,0a -source=2001:700:700:2:92e2:baff:fe48:bde1,00,2e,0a \
   -destination=8.8.8.8 -destination=2606:4700:10::6814:155 \
   -ping -traceroute \
   -tracerouteduration=1000 \
   -tracerouteinitialmaxttl=4 \
   -traceroutefinalmaxttl=32 \
   -tracerouteincrementmaxttl=4 \
   -pinginterval=1000 \
   -pingexpiration=7500 \
   -pingttl=56 \
   -resultsdirectory=/tmp/xy \
   -resultstransactionlength=20 \
   -verbose
