#!/bin/sh

make -j8 hipercontracer && \
rm -f core && \
sudo ./hipercontracer \
   -# 12345678 \
   --resultsdirectory results \
   --resultstransactionlength 300 \
   --resultstimestampdepth=4 \
   --iomodule icmp \
   --source 0.0.0.0 \
   --source :: \
   --destination 1.1.1.1 \
   --destination 8.8.8.8 \
   --destination 193.99.144.80 \
   --destination 136.186.1.10 \
   --destination 77.36.144.2 \
   --destination 94.247.111.11 \
   --destination 185.96.240.128 \
   --destination 103.147.22.34 \
   --destination 94.247.111.11 \
   --destination 10.99.99.99 \
   --destination 2001:4860:4860::8888 \
   --destination 2a02:2e0:3fe:1001:7777:772e:2:85 \
   --destination 2606:4700::6810:2c63 \
   --traceroute \
   --ping \
   --tracerouteduration 1000 \
   --tracerouteinitialmaxttl 4 \
   --traceroutefinalmaxttl 32 \
   --tracerouteincrementmaxttl 4 \
   --pinginterval 1000 \
   --pingexpiration 7500 \
   --pingttl 56 \
   --pingburst 2 \
   $@
