#!/bin/sh

make -j8 && \
sudo ./debug.memcheck ./hipercontracer \
   -source=172.16.0.206 \
   -destination=8.8.8.8 -destination=193.99.144.80 -destination=132.252.181.87 -destination=172.31.255.254 -destination=210.37.45.148 \
   -ping -traceroute \
   -tracerouteduration=1000 \
   -tracerouteinitialmaxttl=4 \
   -traceroutefinalmaxttl=32 \
   -tracerouteincrementmaxttl=4 \
   -pinginterval=1000 \
   -pingexpiration=7500 \
   -pingttl=56 \
   -resultsdirectory=/tmp/xy \
   -resultstransactionlength=20 \
   -quiet
