#!/bin/sh


make -j8 hipercontracer && \
rm -f core && \
sudo ./debug.memcheck ./hipercontracer \
   -# 12345678 \
   --iomodule udp --iomodule icmp \
   -source=0.0.0.0 \
   -destination=8.8.8.8 -destination=193.99.144.80 -destination=132.252.181.87 -destination=10.254.254.254 \
   -destination=91.189.93.5 -destination=128.112.139.90 -destination=4.31.198.44 -destination=136.186.1.10 \
   -destination=101.4.112.170 -destination=77.36.144.2 -destination=10.99.99.99 \
   -source=:: \
   -destination=2400:cb00:2048:1::6814:155 -destination=2a02:2e0:3fe:1001:7777:772e:2:85 -destination=2a00:1450:400f:805::2004 \
   -traceroute \
   -ping \
   -tracerouteduration=1000 \
   -tracerouteinitialmaxttl=4 \
   -traceroutefinalmaxttl=32 \
   -tracerouteincrementmaxttl=4 \
   -pinginterval=1000 \
   -pingexpiration=7500 \
   -pingttl=56 \
   -pingburst=2 \
   -resultsdirectory=results \
   $@
