#!/bin/sh

make -j8 && \
# sudo ./debug.memcheck ./hipercontracer \
sudo ./hipercontracer \
   -verbose \
   -source=172.16.0.240 \
   -destination=104.20.0.85 \
   -traceroute \
   -tracerouteduration=2000 \
   -tracerouterounds=5 \
   -tracerouteinitialmaxttl=4 \
   -traceroutefinalmaxttl=32 \
   -tracerouteincrementmaxttl=4 \
   -resultsdirectory=/tmp/xy \
   -resultstransactionlength=20 \
   $@
