#!/bin/sh

make -j8 && \
sudo ./debug.helgrind ./hipercontracer \
   -source=10.1.1.51 \
   -destination=10.1.1.6 \
   -destination=10.1.1.7 \
   -destination=10.1.1.8 \
   -traceroute \
   -tracerouteinterval=10000 \
   -tracerouteduration=1000
