#!/usr/bin/python3
# -*- coding: utf-8 -*-

import os
import sys
import io
import datetime
import bz2
import shutil
import operator
from ipaddress import ip_address


inputFile = bz2.open('/tmp/xy/Ping-172.16.0.206-20180109T132910.765228-000000001.results.bz2', 'rt')

output = {}

inputType = ''
lineNumber = 0
for inputLine in inputFile.readlines():
   lineNumber = lineNumber + 1
   tuples = inputLine.split(' ')
   if len(tuples) > 0:
      if tuples[0] == '#P':
         if len(tuples) >= 6:
            if inputType == '':
               inputType = 'Ping'
            elif inputType != 'Ping':
               error('ERROR: Multiple input types in the same file?!')

            sourceIP      = ip_address(tuples[1])
            destinationIP = ip_address(tuples[2])
            timeStamp     = int(tuples[3], 16)
            status        = int(tuples[4])
            rtt           = int(tuples[5])
            assert ('0x' + tuples[3]) == hex(timeStamp)
            # print('ping', sourceIP, destinationIP, timeStamp, hex(timeStamp), tuples[3], status, rtt)
            
            timeStampDT  = datetime.datetime(1970, 1, 1, 0, 0, 0, 0) +  datetime.timedelta(microseconds = timeStamp)
            timeStampStr = timeStampDT.strftime("%Y%m%dT%H%M%S.%f")

            output[str(sourceIP) + '-' + str(destinationIP) + '-' + str(timeStamp)] = '(' + \
               '\'' + str(sourceIP)      + '\',' + \
               '\'' + str(destinationIP) + '\',' + \
               '\'' + timeStampStr       + '\',' + \
               str(status) + ',' + \
               str(rtt) + \
               ')'

         else:
            error('ERROR: Bad input for Ping in line ' + str(lineNumer))
      else:
         error('ERROR: Unexpected input in line ' + str(lineNumer))


#if inputType == 'Ping':
   

result = sorted(output.items(), key=operator.itemgetter(0))
for r in result:
   print(r[1])
