.\" ========================================================================
.\"    _   _ _ ____            ____          _____
.\"   | | | (_)  _ \ ___ _ __ / ___|___  _ _|_   _| __ __ _  ___ ___ _ __
.\"   | |_| | | |_) / _ \ '__| |   / _ \| '_ \| || '__/ _` |/ __/ _ \ '__|
.\"   |  _  | |  __/  __/ |  | |__| (_) | | | | || | | (_| | (_|  __/ |
.\"   |_| |_|_|_|   \___|_|   \____\___/|_| |_|_||_|  \__,_|\___\___|_|
.\"
.\"      ---  High-Performance Connectivity Tracer (HiPerConTracer)  ---
.\"                https://www.nntb.no/~dreibh/hipercontracer/
.\" ========================================================================
.\"
.\" High-Performance Connectivity Tracer (HiPerConTracer)
.\" Copyright (C) 2015-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd April 11, 2025
.Dt udp-echo-server 1
.Os udp-echo-server
.\" ###### Name #############################################################
.Sh NAME
.Nm udp-echo-server
.Nd Simple UDP Echo Server
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm udp-echo-server
.Op Fl L Ar level | Fl Fl loglevel Ar level
.Op Fl Z | Fl Fl logcolor Ar on|off
.Op Fl O Ar file | Fl Fl logfile Ar file
.Op Fl q | Fl Fl quiet
.Op Fl v | Fl Fl verbose
.Op Fl U Ar user|uid | Fl Fl user Ar user|uid
.Op Fl A Ar address | Fl Fl address Ar address
.Op Fl P Ar port | Fl Fl port Ar port
.Op Fl f Ar port | Fl Fl from-port Ar port
.Op Fl t Ar port | Fl Fl to-port Ar port
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm udp-echo-server
is a simple UDP Echo server. It can be used as endpoint for HiPerConTracer
UDP Ping/Traceroute.
Note, for security reasons, udp-echo-server only responds to source ports
>= 1024, to avoid using the server in attacks, like spoofing a packet from
another Echo server (port 7) to create a flooding loop. Also, packets
from the same port as the listening port are ignored.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments may be provided:
.Bl -tag -width indent
.It Fl L Ar level | Fl Fl loglevel Ar level
Sets the minimum logging level to the provided value: 0=trace, 1=debug, 2=info, 3=warning, 4=error, 5=fatal.
.It Fl q | Fl Fl quiet
Sets the minimum logging level to 3 (warning).
.It Fl v | Fl Fl verbose
Sets the minimum logging level to 0 (trace).
.It Fl Z Ar on|off| Fl Fl logcolor Ar on|off
Enables (on) or disables (off) the usage of ANSI color escape sequences to colorise the log output according to its level.
.It Fl O Ar file | Fl Fl logfile Ar file
Sets a file name for appending the log output to. If a file is set, no log output is made to the console. Otherwise, all log output will be written to the console.
.It Fl U Ar user|uid | Fl Fl user Ar user|uid
After startup, the server uses UID and GID of the given user (by name or GID).
.It Fl A Ar address | Fl Fl address Ar address
Sets the local address (default: ::).
.It Fl P Ar port | Fl Fl port Ar port
Sets the local port (default: 7).
.It Fl P Ar port | Fl Fl from-port Ar port
Sets the first local port of a range (default: 7).
.It Fl P Ar port | Fl Fl to-port Ar port
Sets the last local port of a range (default: 0; 0 uses the "from" port).
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It udp-echo-server
.It udp-echo-server --address 192.168.1.1 --port 7777
.It udp-echo-server --address 3ffe::1:2:3 --port 7777
.It udp-echo-server --address :: --user nornetpp
.It udp-echo-server --address 3ffe::1:2:3 --from-port 10000 --to-port 10999
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/hipercontracer
.br
mailto://dreibh@simula.no
.br
